# SPDX-License-Identifier: MIT
# Copyright Noble Factor. All rights reserved.

# gen-receiver.star - Generate receivers and operations from Go structs
#
# Reads a Go implementation struct's methods via go.methods(), then calls
# go.generate() to produce plan receivers, graph operations, and real-time
# receivers.

# Methods from starlark.Value and starlark.HasAttrs -- always excluded.
# These are generated by the templates themselves.
SKIP_METHODS = [
    "String", "Type", "Freeze", "Truth", "Hash",
    "Attr", "AttrNames",
]

# Common struct name suffixes to strip when deriving category
STRIP_SUFFIXES = ["Ops", "Impl", "Service", "Handler"]

# Template to output filename mapping
TEMPLATE_FILES = {
    "plan_receiver": "plan_%s_gen.go",
    "graph_ops": "ops_%s_gen.go",
    "realtime_receiver": "receiver_%s_gen.go",
}

# Template to default package mapping
TEMPLATE_PACKAGES = {
    "plan_receiver": "starlark",
    "graph_ops": "execution",
    "realtime_receiver": "starlark",
}

def to_snake(name):
    """Convert CamelCase to snake_case."""
    result = []
    for i in range(len(name)):
        ch = name[i]
        if ch.isupper():
            if i > 0:
                prev = name[i - 1]
                if prev.islower():
                    result.append("_")
                elif prev.isupper() and i + 1 < len(name) and name[i + 1].islower():
                    result.append("_")
            result.append(ch.lower())
        else:
            result.append(ch)
    return "".join(result)

def run(ctx):
    """Generate receivers and operations from a Go struct."""

    # -------------------------------------------------------------------------
    # Validate required arguments
    # -------------------------------------------------------------------------
    path = ctx.args.get("path", "")
    struct_name = ctx.args.get("struct", "")

    if not path:
        fail("--path is required")
    if not struct_name:
        fail("--struct is required")

    # -------------------------------------------------------------------------
    # Discover and filter methods
    # -------------------------------------------------------------------------
    methods = go.methods(path, receiver_type=struct_name)

    if len(methods) == 0:
        fail("no methods found for " + struct_name + " in " + path)

    # Filter to public methods, excluding skip list
    methods_filter = ctx.args.get("methods", "")
    include_list = []
    if methods_filter:
        include_list = methods_filter.split(",")

    filtered = []
    for m in methods:
        # Skip non-public methods (lowercase first letter)
        if m.name[0].islower():
            continue
        # Skip starlark.Value / HasAttrs interface methods
        if m.name in SKIP_METHODS:
            continue
        # Apply inclusion filter if specified
        if include_list and m.name not in include_list:
            continue
        filtered.append(m)

    if len(filtered) == 0:
        fail("no eligible methods after filtering for " + struct_name)

    note("Found " + str(len(filtered)) + " methods for " + struct_name)

    # -------------------------------------------------------------------------
    # Derive names and build descriptor
    # -------------------------------------------------------------------------

    # Strip common suffixes from struct name
    struct_short = struct_name
    for suffix in STRIP_SUFFIXES:
        if struct_short.endswith(suffix) and len(struct_short) > len(suffix):
            struct_short = struct_short[:-len(suffix)]
            break

    # Category override or derive from struct name
    category = ctx.args.get("category", "")
    if not category:
        category = to_snake(struct_short)

    pkg_override = ctx.args.get("package", "")

    # Build method descriptors
    method_descriptors = []
    for m in filtered:
        params = []
        for p in m.params:
            params.append({
                "name": p.name,
                "type": p.type,
                "variadic": p.variadic,
            })
        method_descriptors.append({
            "name": m.name,
            "returns": m.returns,
            "doc": m.doc,
            "params": params,
        })

    # -------------------------------------------------------------------------
    # Generate code for each template
    # -------------------------------------------------------------------------
    templates_str = ctx.args.get("templates", "plan_receiver,graph_ops,realtime_receiver")
    templates = templates_str.split(",")
    output_dir = ctx.args.get("output", "")
    write_files = ctx.args.get("write", "false") == "true"

    for tmpl in templates:
        tmpl = tmpl.strip()
        if tmpl not in TEMPLATE_FILES:
            fail("unknown template: " + tmpl + " (valid: plan_receiver, graph_ops, realtime_receiver)")

        # Derive namespace
        if tmpl == "plan_receiver":
            namespace = "plan." + category
        else:
            namespace = category

        # Derive package
        pkg = pkg_override if pkg_override else TEMPLATE_PACKAGES[tmpl]

        descriptor = {
            "package": pkg,
            "category": category,
            "struct_name": struct_short,
            "namespace": namespace,
            "methods": method_descriptors,
        }

        note("Generating " + tmpl + " for " + struct_short + "...")
        code = go.generate(tmpl, descriptor)

        filename = TEMPLATE_FILES[tmpl] % category
        if write_files and output_dir:
            out_path = output_dir + "/" + filename
            file.write(out_path, code)
            success("Wrote " + out_path)
        else:
            note("--- " + filename + " ---")
            note(code)

    success("Done. Generated " + str(len(templates)) + " file(s) for " + struct_short)
