// SPDX-License-Identifier: MIT
// Copyright Noble Factor. All rights reserved.

package config

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

const generatedHeader = `# GENERATED BY star lint sync - DO NOT EDIT
# Source: star/config.yaml
# Regenerate: star lint sync
`

// SyncResult describes what was synced.
type SyncResult struct {
	GolangciLint    string // Path to generated .golangci.yaml
	MarkdownLint    string // Path to generated .markdownlint-cli2.yaml
	PrecommitConfig string // Path to generated .pre-commit-config.yaml
	FilesGenerated  int
}

// syncFromConfig generates tool-specific config files using ConfigAccessor paths.
func syncFromConfig(c *Config) (*SyncResult, error) {
	result := &SyncResult{}

	// Sync golangci-lint config if configured
	goConfig := c.Accessor("lint.go").Map("config")
	if len(goConfig) > 0 {
		path, err := syncGolangciLint(goConfig)
		if err != nil {
			return nil, fmt.Errorf("syncing golangci-lint config: %w", err)
		}
		result.GolangciLint = path
		result.FilesGenerated++
	}

	// Sync markdownlint config if configured
	mdConfig := c.Accessor("lint.markdown").Map("config")
	if len(mdConfig) > 0 {
		path, err := syncMarkdownLint(mdConfig)
		if err != nil {
			return nil, fmt.Errorf("syncing markdownlint config: %w", err)
		}
		result.MarkdownLint = path
		result.FilesGenerated++
	}

	// Sync pre-commit config if hooks are configured
	hooks := c.Accessor("precommit").Get("hooks")
	if hookSlice, ok := hooks.([]interface{}); ok && len(hookSlice) > 0 {
		path, err := syncPrecommitConfig(hookSlice)
		if err != nil {
			return nil, fmt.Errorf("syncing pre-commit config: %w", err)
		}
		result.PrecommitConfig = path
		result.FilesGenerated++
	}

	return result, nil
}

// syncGolangciLint writes .golangci.yaml from config values.
func syncGolangciLint(cfg map[string]interface{}) (string, error) {
	root := GitWorkspaceRoot()
	if root == "" {
		root = "."
	}
	path := filepath.Join(root, ".golangci.yaml")

	data, err := yaml.Marshal(cfg)
	if err != nil {
		return "", err
	}

	content := generatedHeader + string(data)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return "", err
	}

	return path, nil
}

// syncMarkdownLint writes .markdownlint-cli2.yaml from config values.
func syncMarkdownLint(cfg map[string]interface{}) (string, error) {
	root := GitWorkspaceRoot()
	if root == "" {
		root = "."
	}
	path := filepath.Join(root, ".markdownlint-cli2.yaml")

	// markdownlint-cli2 expects config under a "config" key
	wrapper := map[string]interface{}{
		"config": cfg,
	}

	data, err := yaml.Marshal(wrapper)
	if err != nil {
		return "", err
	}

	content := generatedHeader + string(data)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return "", err
	}

	return path, nil
}

// precommitRepo represents a repo in .pre-commit-config.yaml.
type precommitRepo struct {
	Repo  string          `yaml:"repo"`
	Hooks []precommitHook `yaml:"hooks"`
}

// precommitHook represents a hook in .pre-commit-config.yaml.
type precommitHook struct {
	ID            string   `yaml:"id"`
	Name          string   `yaml:"name"`
	Entry         string   `yaml:"entry"`
	Language      string   `yaml:"language"`
	PassFilenames bool     `yaml:"pass_filenames,omitempty"`
	Types         []string `yaml:"types,omitempty"`
	Stages        []string `yaml:"stages,omitempty"`
}

// precommitConfig represents the full .pre-commit-config.yaml structure.
type precommitConfig struct {
	Repos []precommitRepo `yaml:"repos"`
}

// syncPrecommitConfig writes .pre-commit-config.yaml from hook values.
func syncPrecommitConfig(hooks []interface{}) (string, error) {
	root := GitWorkspaceRoot()
	if root == "" {
		root = "."
	}
	path := filepath.Join(root, ".pre-commit-config.yaml")

	var pcHooks []precommitHook
	for _, h := range hooks {
		hMap, ok := h.(map[string]interface{})
		if !ok {
			continue
		}
		hook := precommitHook{
			ID:       mapString(hMap, "id"),
			Name:     mapString(hMap, "name"),
			Entry:    mapString(hMap, "entry"),
			Language: mapString(hMap, "language"),
		}
		if hook.Language == "" {
			hook.Language = "system"
		}
		if v, ok := hMap["pass_filenames"].(bool); ok {
			hook.PassFilenames = v
		}
		hook.Types = mapStringSlice(hMap, "types")
		hook.Stages = mapStringSlice(hMap, "stages")
		pcHooks = append(pcHooks, hook)
	}

	cfg := precommitConfig{
		Repos: []precommitRepo{
			{
				Repo:  "local",
				Hooks: pcHooks,
			},
		},
	}

	data, err := yaml.Marshal(cfg)
	if err != nil {
		return "", err
	}

	content := generatedHeader + string(data)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return "", err
	}

	return path, nil
}

// GolangciConfigPath returns the path to use for golangci-lint config.
func GolangciConfigPath(c *Config) string {
	goConfig := c.Accessor("lint.go").Map("config")
	if len(goConfig) > 0 {
		root := GitWorkspaceRoot()
		if root == "" {
			root = "."
		}
		return filepath.Join(root, ".golangci.yaml")
	}
	return ""
}

// MarkdownLintConfigPath returns the path to use for markdownlint config.
func MarkdownLintConfigPath(c *Config) string {
	mdConfig := c.Accessor("lint.markdown").Map("config")
	if len(mdConfig) > 0 {
		root := GitWorkspaceRoot()
		if root == "" {
			root = "."
		}
		return filepath.Join(root, ".markdownlint-cli2.yaml")
	}
	return ""
}

// Clean removes generated config files.
func Clean() error {
	root := GitWorkspaceRoot()
	if root == "" {
		root = "."
	}

	files := []string{
		filepath.Join(root, ".golangci.yaml"),
		filepath.Join(root, ".markdownlint-cli2.yaml"),
		filepath.Join(root, ".pre-commit-config.yaml"),
	}

	for _, f := range files {
		data, err := os.ReadFile(f)
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			return err
		}

		if len(data) > len(generatedHeader) && string(data[:len(generatedHeader)]) == generatedHeader {
			if err := os.Remove(f); err != nil {
				return err
			}
		}
	}

	return nil
}

// EnsureGitignore ensures generated files are in .gitignore.
func EnsureGitignore() error {
	root := GitWorkspaceRoot()
	if root == "" {
		root = "."
	}

	gitignorePath := filepath.Join(root, ".gitignore")
	entries := []string{
		".golangci.yaml",
		".markdownlint-cli2.yaml",
		".pre-commit-config.yaml",
	}

	data, err := os.ReadFile(gitignorePath)
	if err != nil && !os.IsNotExist(err) {
		return err
	}

	content := string(data)
	var toAdd []string

	for _, entry := range entries {
		if !containsLine(content, entry) {
			toAdd = append(toAdd, entry)
		}
	}

	if len(toAdd) == 0 {
		return nil
	}

	f, err := os.OpenFile(gitignorePath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return err
	}
	defer f.Close()

	if len(data) > 0 && data[len(data)-1] != '\n' {
		if _, err := f.WriteString("\n"); err != nil {
			return err
		}
	}
	if _, err := f.WriteString("\n# Generated by star lint sync\n"); err != nil {
		return err
	}
	for _, entry := range toAdd {
		if _, err := f.WriteString(entry + "\n"); err != nil {
			return err
		}
	}

	return nil
}

// containsLine checks if content contains a line matching entry.
func containsLine(content, entry string) bool {
	lines := filepath.SplitList(content)
	for _, line := range lines {
		if line == entry {
			return true
		}
	}
	return len(content) > 0 && (content == entry ||
		len(content) > len(entry) &&
			(content[:len(entry)+1] == entry+"\n" ||
				containsSubstring(content, "\n"+entry+"\n") ||
				(len(content) > len(entry) && content[len(content)-len(entry)-1:] == "\n"+entry)))
}

func containsSubstring(s, substr string) bool {
	return len(s) >= len(substr) && findSubstring(s, substr) >= 0
}

func findSubstring(s, substr string) int {
	for i := 0; i <= len(s)-len(substr); i++ {
		if s[i:i+len(substr)] == substr {
			return i
		}
	}
	return -1
}

// mapString extracts a string from a map.
func mapString(m map[string]interface{}, key string) string {
	if v, ok := m[key].(string); ok {
		return v
	}
	return ""
}

// mapStringSlice extracts a string slice from a map.
func mapStringSlice(m map[string]interface{}, key string) []string {
	v, ok := m[key]
	if !ok {
		return nil
	}
	switch s := v.(type) {
	case []string:
		return s
	case []interface{}:
		var result []string
		for _, item := range s {
			if str, ok := item.(string); ok {
				result = append(result, str)
			}
		}
		return result
	}
	return nil
}
