// SPDX-License-Identifier: MIT
// Copyright Noble Factor. All rights reserved.

package config

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

const generatedHeader = `# GENERATED BY star lint sync - DO NOT EDIT
# Source: star.yaml
# Regenerate: star lint sync
`

// SyncResult describes what was synced.
type SyncResult struct {
	GolangciLint  string // Path to generated .golangci.yaml
	MarkdownLint  string // Path to generated .markdownlint-cli2.yaml
	PrecommitConfig string // Path to generated .pre-commit-config.yaml
	FilesGenerated int
}

// Sync writes tool-specific config files from star.yaml.
func (c *Config) Sync() (*SyncResult, error) {
	result := &SyncResult{}

	// Sync golangci-lint config if configured
	if c.Lint.Go.Config != nil && len(c.Lint.Go.Config) > 0 {
		path, err := c.syncGolangciLint()
		if err != nil {
			return nil, fmt.Errorf("syncing golangci-lint config: %w", err)
		}
		result.GolangciLint = path
		result.FilesGenerated++
	}

	// Sync markdownlint config if configured
	if c.Lint.Markdown.Config != nil && len(c.Lint.Markdown.Config) > 0 {
		path, err := c.syncMarkdownLint()
		if err != nil {
			return nil, fmt.Errorf("syncing markdownlint config: %w", err)
		}
		result.MarkdownLint = path
		result.FilesGenerated++
	}

	// Sync pre-commit config if hooks are configured
	if len(c.Precommit.Hooks) > 0 {
		path, err := c.syncPrecommitConfig()
		if err != nil {
			return nil, fmt.Errorf("syncing pre-commit config: %w", err)
		}
		result.PrecommitConfig = path
		result.FilesGenerated++
	}

	return result, nil
}

// syncGolangciLint writes .golangci.yaml from star.yaml config.
func (c *Config) syncGolangciLint() (string, error) {
	path := ".golangci.yaml"

	data, err := yaml.Marshal(c.Lint.Go.Config)
	if err != nil {
		return "", err
	}

	content := generatedHeader + string(data)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return "", err
	}

	return path, nil
}

// syncMarkdownLint writes .markdownlint-cli2.yaml from star.yaml config.
func (c *Config) syncMarkdownLint() (string, error) {
	path := ".markdownlint-cli2.yaml"

	// markdownlint-cli2 expects config under a "config" key
	wrapper := map[string]interface{}{
		"config": c.Lint.Markdown.Config,
	}

	data, err := yaml.Marshal(wrapper)
	if err != nil {
		return "", err
	}

	content := generatedHeader + string(data)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return "", err
	}

	return path, nil
}

// precommitRepo represents a repo in .pre-commit-config.yaml.
type precommitRepo struct {
	Repo  string           `yaml:"repo"`
	Hooks []precommitHook  `yaml:"hooks"`
}

// precommitHook represents a hook in .pre-commit-config.yaml.
type precommitHook struct {
	ID            string   `yaml:"id"`
	Name          string   `yaml:"name"`
	Entry         string   `yaml:"entry"`
	Language      string   `yaml:"language"`
	PassFilenames bool     `yaml:"pass_filenames,omitempty"`
	Types         []string `yaml:"types,omitempty"`
	Stages        []string `yaml:"stages,omitempty"`
}

// precommitConfig represents the full .pre-commit-config.yaml structure.
type precommitConfig struct {
	Repos []precommitRepo `yaml:"repos"`
}

// syncPrecommitConfig writes .pre-commit-config.yaml from star.yaml config.
func (c *Config) syncPrecommitConfig() (string, error) {
	path := ".pre-commit-config.yaml"

	// Convert our hooks to pre-commit format
	var hooks []precommitHook
	for _, h := range c.Precommit.Hooks {
		hook := precommitHook{
			ID:            h.ID,
			Name:          h.Name,
			Entry:         h.Entry,
			Language:      h.Language,
			PassFilenames: h.PassFilenames,
			Types:         h.Types,
			Stages:        h.Stages,
		}
		// Set defaults
		if hook.Language == "" {
			hook.Language = "system"
		}
		hooks = append(hooks, hook)
	}

	cfg := precommitConfig{
		Repos: []precommitRepo{
			{
				Repo:  "local",
				Hooks: hooks,
			},
		},
	}

	data, err := yaml.Marshal(cfg)
	if err != nil {
		return "", err
	}

	content := generatedHeader + string(data)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return "", err
	}

	return path, nil
}

// GolangciConfigPath returns the path to use for golangci-lint config.
// Returns the generated path if star.yaml has config, otherwise empty.
func (c *Config) GolangciConfigPath() string {
	if c.Lint.Go.Config != nil && len(c.Lint.Go.Config) > 0 {
		return ".golangci.yaml"
	}
	return ""
}

// MarkdownLintConfigPath returns the path to use for markdownlint config.
// Returns the generated path if star.yaml has config, otherwise empty.
func (c *Config) MarkdownLintConfigPath() string {
	if c.Lint.Markdown.Config != nil && len(c.Lint.Markdown.Config) > 0 {
		return ".markdownlint-cli2.yaml"
	}
	return ""
}

// Clean removes generated config files.
func Clean() error {
	files := []string{
		".golangci.yaml",
		".markdownlint-cli2.yaml",
		".pre-commit-config.yaml",
	}

	for _, f := range files {
		// Only remove if it has our header
		data, err := os.ReadFile(f)
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			return err
		}

		if len(data) > len(generatedHeader) && string(data[:len(generatedHeader)]) == generatedHeader {
			if err := os.Remove(f); err != nil {
				return err
			}
		}
	}

	return nil
}

// EnsureGitignore ensures generated files are in .gitignore.
func EnsureGitignore() error {
	gitignorePath := ".gitignore"
	entries := []string{
		".golangci.yaml",
		".markdownlint-cli2.yaml",
		".pre-commit-config.yaml",
	}

	// Read existing .gitignore
	data, err := os.ReadFile(gitignorePath)
	if err != nil && !os.IsNotExist(err) {
		return err
	}

	content := string(data)
	var toAdd []string

	for _, entry := range entries {
		if !containsLine(content, entry) {
			toAdd = append(toAdd, entry)
		}
	}

	if len(toAdd) == 0 {
		return nil
	}

	// Append to .gitignore
	f, err := os.OpenFile(gitignorePath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return err
	}
	defer f.Close()

	// Add header comment if adding entries
	if len(data) > 0 && data[len(data)-1] != '\n' {
		if _, err := f.WriteString("\n"); err != nil {
			return err
		}
	}
	if _, err := f.WriteString("\n# Generated by star lint sync\n"); err != nil {
		return err
	}
	for _, entry := range toAdd {
		if _, err := f.WriteString(entry + "\n"); err != nil {
			return err
		}
	}

	return nil
}

// containsLine checks if content contains a line matching entry.
func containsLine(content, entry string) bool {
	lines := filepath.SplitList(content)
	for _, line := range lines {
		if line == entry {
			return true
		}
	}
	// Simple substring check as fallback
	return len(content) > 0 && (content == entry ||
		len(content) > len(entry) &&
		(content[:len(entry)+1] == entry+"\n" ||
		 containsSubstring(content, "\n"+entry+"\n") ||
		 (len(content) > len(entry) && content[len(content)-len(entry)-1:] == "\n"+entry)))
}

func containsSubstring(s, substr string) bool {
	return len(s) >= len(substr) && findSubstring(s, substr) >= 0
}

func findSubstring(s, substr string) int {
	for i := 0; i <= len(s)-len(substr); i++ {
		if s[i:i+len(substr)] == substr {
			return i
		}
	}
	return -1
}
