// Code generated by make generate-register; DO NOT EDIT.

// Package provider triggers init() in all provider packages via blank imports.
// Importing this package causes every provider to call op.AnnounceReceiver(),
// making them available via op.Receivers().
package provider

import (
	_ "github.com/NobleFactor/devlore-cli/pkg/op/provider"
	_ "github.com/NobleFactor/noblefactor-ops/internal/starlark/provider/commands/gen"
	_ "github.com/NobleFactor/noblefactor-ops/internal/starlark/provider/config/gen"
	_ "github.com/NobleFactor/noblefactor-ops/internal/starlark/provider/goast/gen"
	_ "github.com/NobleFactor/noblefactor-ops/internal/starlark/provider/lint/gen"
	_ "github.com/NobleFactor/noblefactor-ops/internal/starlark/provider/setup/gen"
	_ "github.com/NobleFactor/noblefactor-ops/internal/starlark/provider/shellcheck/gen"
)
