// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 Noble Factor. All rights reserved.

package starlark

import (
	"context"
	_ "embed"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"go.starlark.net/starlark"
	"go.starlark.net/starlarkstruct"

	"github.com/NobleFactor/noblefactor-ops/internal/cli"
)

// lintModule returns the lint module with static analysis operations.
func lintModule() *starlarkstruct.Module {
	return &starlarkstruct.Module{
		Name: "lint",
		Members: starlark.StringDict{
			"go":           starlark.NewBuiltin("lint.go", lintGo),
			"ensure_tools": starlark.NewBuiltin("lint.ensure_tools", lintEnsureTools),
		},
	}
}

// =============================================================================
// DEFAULT CONFIGURATION
// =============================================================================

// defaultGolangciConfig is the canonical golangci-lint configuration for
// NobleFactor projects. This matches devlore-cli's .golangci.yaml.
const defaultGolangciConfig = `# SPDX-License-Identifier: MIT
# golangci-lint v2 configuration for NobleFactor Go projects
#
# Objectives:
#   - Low complexity (gocyclo <= 15, gocognit <= 20)
#   - No dead or unused code
#   - No redundant code
#   - Clean formatting
#
# Generated by: star lint go

version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

formatters:
  enable:
    - gofmt
    - goimports

linters:
  default: none
  enable:
    # Essential
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused

    # Complexity
    - gocyclo
    - gocognit

    # Dead/redundant code
    - unparam
    - unconvert

    # Code quality
    - gocritic
    - gosec
    - misspell
    - nilerr
    - bodyclose
    - durationcheck
    - errorlint
    - noctx

    # Style
    - revive
    - whitespace

  settings:
    gocyclo:
      min-complexity: 15

    gocognit:
      min-complexity: 20

    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
      disabled-checks:
        - whyNoLint
        - hugeParam

    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: increment-decrement
        - name: indent-error-flow
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: var-declaration
        - name: var-naming

    gosec:
      excludes:
        - G104
        - G304

    misspell:
      locale: US

    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - io.Copy
        - (*os.File).Close
        - (io.Closer).Close

  exclusions:
    generated: lax
    rules:
      # Test files can have higher complexity
      - path: _test\.go
        linters:
          - gocyclo
          - gocognit
          - errcheck
          - gosec

      # Generated files
      - path: \.pb\.go$
        linters:
          - all

    paths:
      - vendor
      - testdata
      - .git

output:
  formats:
    text:
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
`

// =============================================================================
// TOOL MANAGEMENT
// =============================================================================

// ToolInfo describes a required lint tool.
type ToolInfo struct {
	Name        string
	Binary      string
	InstallCmd  string
	InstallNote string
}

// requiredTools lists all tools needed for linting.
var requiredTools = []ToolInfo{
	{
		Name:       "golangci-lint",
		Binary:     "golangci-lint",
		InstallCmd: "go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest",
	},
	{
		Name:       "shellcheck",
		Binary:     "shellcheck",
		InstallCmd: getShellcheckInstallCmd(),
	},
	{
		Name:       "shfmt",
		Binary:     "shfmt",
		InstallCmd: "go install mvdan.cc/sh/v3/cmd/shfmt@latest",
	},
}

// getShellcheckInstallCmd returns the platform-specific install command for shellcheck.
func getShellcheckInstallCmd() string {
	switch runtime.GOOS {
	case "darwin":
		return "brew install shellcheck"
	case "linux":
		return "sudo apt-get install shellcheck  # or: sudo dnf install ShellCheck"
	default:
		return "See https://github.com/koalaman/shellcheck#installing"
	}
}

// checkTool verifies a tool is installed and returns its path or empty string.
func checkTool(binary string) string {
	path, err := exec.LookPath(binary)
	if err != nil {
		return ""
	}
	return path
}

// lintEnsureTools checks that all required lint tools are installed.
// Returns a struct with status of each tool.
func lintEnsureTools(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	if err := starlark.UnpackArgs("lint.ensure_tools", args, kwargs); err != nil {
		return nil, err
	}

	var toolStatus []starlark.Value
	allInstalled := true
	var missingTools []ToolInfo

	for _, tool := range requiredTools {
		path := checkTool(tool.Binary)
		installed := path != ""
		if !installed {
			allInstalled = false
			missingTools = append(missingTools, tool)
		}

		toolStatus = append(toolStatus, starlarkstruct.FromStringDict(starlarkstruct.Default, starlark.StringDict{
			"name":        starlark.String(tool.Name),
			"installed":   starlark.Bool(installed),
			"path":        starlark.String(path),
			"install_cmd": starlark.String(tool.InstallCmd),
		}))
	}

	// Build install instructions for missing tools
	var instructions []starlark.Value
	for _, tool := range missingTools {
		instructions = append(instructions, starlark.String(tool.InstallCmd))
	}

	return starlarkstruct.FromStringDict(starlarkstruct.Default, starlark.StringDict{
		"all_installed": starlark.Bool(allInstalled),
		"tools":         starlark.NewList(toolStatus),
		"install_cmds":  starlark.NewList(instructions),
	}), nil
}

// ensureGolangciConfig creates .golangci.yaml if it doesn't exist.
// Returns the path to the config file and whether it was created.
func ensureGolangciConfig() (string, bool, error) {
	configPath := ".golangci.yaml"

	// Check if config exists
	if _, err := os.Stat(configPath); err == nil {
		return configPath, false, nil
	}

	// Also check for .golangci.yml variant
	if _, err := os.Stat(".golangci.yml"); err == nil {
		return ".golangci.yml", false, nil
	}

	// Create default config
	if err := os.WriteFile(configPath, []byte(defaultGolangciConfig), 0o644); err != nil {
		return "", false, fmt.Errorf("creating %s: %w", configPath, err)
	}

	return configPath, true, nil
}

// =============================================================================
// GO LINTING (golangci-lint)
// =============================================================================

// GolangCILintOutput represents the JSON output from golangci-lint.
type GolangCILintOutput struct {
	Issues []GolangCILintIssue `json:"Issues"`
}

// GolangCILintIssue represents a single golangci-lint finding.
type GolangCILintIssue struct {
	FromLinter  string               `json:"FromLinter"`
	Text        string               `json:"Text"`
	Severity    string               `json:"Severity"`
	SourceLines []string             `json:"SourceLines"`
	Pos         GolangCILintPosition `json:"Pos"`
}

// GolangCILintPosition represents the position of an issue.
type GolangCILintPosition struct {
	Filename string `json:"Filename"`
	Offset   int    `json:"Offset"`
	Line     int    `json:"Line"`
	Column   int    `json:"Column"`
}

// lintGo runs golangci-lint on Go code and returns structured issues.
//
// On first run, creates .golangci.yaml with NobleFactor defaults if missing.
// Also checks that golangci-lint is installed.
//
// Args:
//   - path: Path to lint (default: "./...")
//   - config: Path to config file (optional, uses .golangci.yaml by default)
//
// Returns:
//   - A struct with:
//   - issues: List of issues found
//   - error_count, warning_count
//   - passed: True if no errors/warnings
//   - total_count: Total number of issues
//   - config_created: True if .golangci.yaml was created
func lintGo(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var path, config string
	if err := starlark.UnpackArgs("lint.go", args, kwargs, "path?", &path, "config?", &config); err != nil {
		return nil, err
	}

	if path == "" {
		path = "./..."
	}

	// Check if golangci-lint is available
	if checkTool("golangci-lint") == "" {
		return nil, fmt.Errorf("lint.go: golangci-lint not installed\n  Install: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest")
	}

	// Ensure config exists (create default if missing)
	var configCreated bool
	if config == "" {
		var err error
		config, configCreated, err = ensureGolangciConfig()
		if err != nil {
			return nil, fmt.Errorf("lint.go: %w", err)
		}
		if configCreated {
			cli.Note("created %s with NobleFactor defaults", config)
		}
	}

	// Build command arguments
	// golangci-lint v2 uses --output.json.path for JSON output
	cmdArgs := []string{"run", "--output.json.path", "stdout"}
	if config != "" {
		// Use absolute path if not already absolute
		if !filepath.IsAbs(config) {
			if absConfig, err := filepath.Abs(config); err == nil {
				config = absConfig
			}
		}
		cmdArgs = append(cmdArgs, "--config="+config)
	}
	cmdArgs = append(cmdArgs, path)

	// Run golangci-lint
	cmd := exec.CommandContext(context.Background(), "golangci-lint", cmdArgs...)
	output, err := cmd.Output()

	// golangci-lint exits non-zero when issues are found, so we need to handle that
	// We only fail on actual execution errors (not finding issues)
	var issues []GolangCILintIssue
	if len(output) > 0 {
		var lintOutput GolangCILintOutput
		if jsonErr := json.Unmarshal(output, &lintOutput); jsonErr == nil {
			issues = lintOutput.Issues
		}
	}

	// If there was an error but no output, check if it's a real error
	if err != nil && len(output) == 0 {
		// Try to get stderr for better error message
		if exitErr, ok := err.(*exec.ExitError); ok {
			stderr := string(exitErr.Stderr)
			if stderr != "" {
				return nil, fmt.Errorf("lint.go: golangci-lint failed: %s", strings.TrimSpace(stderr))
			}
		}
	}

	// Count by severity
	var errors, warnings int
	var issueList []starlark.Value
	for _, issue := range issues {
		severity := issue.Severity
		if severity == "" {
			severity = "warning" // Default severity
		}

		switch severity {
		case "error":
			errors++
		default:
			warnings++
		}

		// Convert source lines to Starlark list
		var sourceLines []starlark.Value
		for _, line := range issue.SourceLines {
			sourceLines = append(sourceLines, starlark.String(line))
		}

		issueList = append(issueList, starlarkstruct.FromStringDict(starlarkstruct.Default, starlark.StringDict{
			"file":         starlark.String(issue.Pos.Filename),
			"line":         starlark.MakeInt(issue.Pos.Line),
			"column":       starlark.MakeInt(issue.Pos.Column),
			"message":      starlark.String(issue.Text),
			"linter":       starlark.String(issue.FromLinter),
			"severity":     starlark.String(severity),
			"source_lines": starlark.NewList(sourceLines),
		}))
	}

	passed := errors == 0 && warnings == 0

	return starlarkstruct.FromStringDict(starlarkstruct.Default, starlark.StringDict{
		"issues":         starlark.NewList(issueList),
		"error_count":    starlark.MakeInt(errors),
		"warning_count":  starlark.MakeInt(warnings),
		"total_count":    starlark.MakeInt(len(issues)),
		"passed":         starlark.Bool(passed),
		"config_created": starlark.Bool(configCreated),
	}), nil
}
