// SPDX-License-Identifier: MIT
// Copyright Noble Factor. All rights reserved.

package starlark

import (
	"go/format"
	"strings"
	"testing"

	"go.starlark.net/starlark"
	"go.starlark.net/starlarkstruct"
	"gopkg.in/yaml.v3"
)

// testPlanReceiverTemplate is the planned_receiver template content.
// Matches the reflection-based planned_receiver.go.template in devlore-cli.
const testPlanReceiverTemplate = `// Code generated by go.generate; DO NOT EDIT.

package {{.Package}}

import (
	"reflect"

	"go.starlark.net/starlark"

	"github.com/NobleFactor/devlore-cli/pkg/op"
{{- if .ProviderImport}}
	provider "{{.ProviderImport}}"
{{- end}}
)

func init() {
	op.RegisterBinding(&op.ProviderBinding{
		Name:     "{{.Provider}}",
		Access:   op.Access{{.AccessTitle}},
		Lifetime: op.Lifetime{{.LifetimeTitle}},
		PlannedFactory: func(graph *op.Graph, project string, reg *op.ActionRegistry) starlark.Value {
			return New{{.StructName}}Plan(graph, project, reg)
		},
	})
}

func New{{.StructName}}Plan(graph *op.Graph, project string, reg *op.ActionRegistry) *op.ReflectedPlanned {
	return op.WrapPlanned("{{.Provider}}", reflect.TypeOf((*{{providerTypePrefix .}}Provider)(nil)), graph, project, reg, Params)
}
`

// testGraphActionsTemplate is the graph_actions template content.
// Matches the reflection-based graph_actions.go.template in devlore-cli.
const testGraphActionsTemplate = `// Code generated by go.generate; DO NOT EDIT.

package {{.Package}}

import (
	"github.com/NobleFactor/devlore-cli/pkg/op"
{{- if .ProviderImport}}
	provider "{{.ProviderImport}}"
{{- end}}
)

func init() {
	op.RegisterBinding(&op.ProviderBinding{
		Name: "{{.Provider}}",
		ActionRegistrar: func(reg *op.ActionRegistry) {
			op.RegisterReflectedActions(reg, "{{.Provider}}", &{{providerTypePrefix .}}Provider{}, Params)
		},
	})
}
`

func TestCamelToSnake(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{"Copy", "copy"},
		{"WalkTree", "walk_tree"},
		{"ConfigGet", "config_get"},
		{"HTMLParser", "html_parser"},
		{"ID", "id"},
		{"HTTPSProxy", "https_proxy"},
		{"A", "a"},
		{"ABC", "abc"},
	}
	for _, tc := range tests {
		t.Run(tc.input, func(t *testing.T) {
			got := camelToSnake(tc.input)
			if got != tc.want {
				t.Errorf("camelToSnake(%q) = %q, want %q", tc.input, got, tc.want)
			}
		})
	}
}

func TestValidateReturnSignature(t *testing.T) {
	tests := []struct {
		input   string
		want    string
		wantErr bool
	}{
		{"(string, error)", "string", false},
		{"(bool, error)", "bool", false},
		{"(int, error)", "int", false},
		{"([]string, error)", "[]string", false},
		{"([]byte, error)", "[]byte", false},
		{"error", "", true}, // plain error return rejected — every method must return a Result
		{"string", "", true},
		{"(string, int, error)", "", true},
		{"", "", true},
		{"(error)", "", true},
	}
	for _, tc := range tests {
		t.Run(tc.input, func(t *testing.T) {
			got, err := validateReturnSignature(tc.input)
			if tc.wantErr {
				if err == nil {
					t.Errorf("expected error for %q, got value %q", tc.input, got)
				}
			} else {
				if err != nil {
					t.Errorf("unexpected error for %q: %v", tc.input, err)
				}
				if got != tc.want {
					t.Errorf("validateReturnSignature(%q) = %q, want %q", tc.input, got, tc.want)
				}
			}
		})
	}
}

// buildTestDescriptor creates a Starlark dict descriptor for testing.
func buildTestDescriptor(t *testing.T, methods []map[string]any) *starlark.Dict {
	t.Helper()
	desc := starlark.NewDict(5)
	must(t, desc.SetKey(starlark.String("package"), starlark.String("starlark")))
	must(t, desc.SetKey(starlark.String("provider"), starlark.String("file")))
	must(t, desc.SetKey(starlark.String("struct_name"), starlark.String("File")))
	must(t, desc.SetKey(starlark.String("namespace"), starlark.String("plan.file")))

	var methodsList []starlark.Value
	for _, m := range methods {
		md := starlark.NewDict(4)
		must(t, md.SetKey(starlark.String("name"), starlark.String(m["name"].(string))))
		must(t, md.SetKey(starlark.String("returns"), starlark.String(m["returns"].(string))))
		must(t, md.SetKey(starlark.String("doc"), starlark.String("")))

		var paramsList []starlark.Value
		if params, ok := m["params"].([]map[string]any); ok {
			for _, p := range params {
				pd := starlark.NewDict(3)
				must(t, pd.SetKey(starlark.String("name"), starlark.String(p["name"].(string))))
				must(t, pd.SetKey(starlark.String("type"), starlark.String(p["type"].(string))))
				variadic := false
				if v, ok := p["variadic"].(bool); ok {
					variadic = v
				}
				must(t, pd.SetKey(starlark.String("variadic"), starlark.Bool(variadic)))
				paramsList = append(paramsList, pd)
			}
		}
		must(t, md.SetKey(starlark.String("params"), starlark.NewList(paramsList)))
		if prop, ok := m["property"].(bool); ok && prop {
			must(t, md.SetKey(starlark.String("property"), starlark.Bool(true)))
		}
		methodsList = append(methodsList, md)
	}
	must(t, desc.SetKey(starlark.String("methods"), starlark.NewList(methodsList)))
	return desc
}

// buildImmediateTestDescriptor builds a descriptor for immediate receiver tests.
// Immediate receivers differ from planned: namespace = provider name (no "plan." prefix),
// and impl_type = "Provider" (the type being wrapped).
func buildImmediateTestDescriptor(t *testing.T, methods []map[string]any) *starlark.Dict {
	t.Helper()
	desc := buildTestDescriptor(t, methods)
	must(t, desc.SetKey(starlark.String("namespace"), starlark.String("file")))
	must(t, desc.SetKey(starlark.String("impl_type"), starlark.String("Provider")))
	return desc
}

func must(t *testing.T, err error) {
	t.Helper()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

// extractGenerateResult extracts the result struct from go.generate.
func extractGenerateResult(t *testing.T, result starlark.Value) *starlarkstruct.Struct {
	t.Helper()
	s, ok := result.(*starlarkstruct.Struct)
	if !ok {
		t.Fatalf("expected struct result from go.generate, got %T", result)
	}
	return s
}

// extractGeneratedCode extracts the "code" field from go.generate's result struct.
func extractGeneratedCode(t *testing.T, result starlark.Value) string {
	t.Helper()
	s := extractGenerateResult(t, result)
	codeVal, err := s.Attr("code")
	if err != nil {
		t.Fatalf("result struct missing 'code' attr: %v", err)
	}
	code, ok := starlark.AsString(codeVal)
	if !ok {
		t.Fatalf("expected string 'code' attr, got %T", codeVal)
	}
	return code
}

// extractFlaggedMethods extracts the "flagged" list from go.generate's result struct.
func extractFlaggedMethods(t *testing.T, result starlark.Value) []string {
	t.Helper()
	s := extractGenerateResult(t, result)
	flaggedVal, err := s.Attr("flagged")
	if err != nil {
		t.Fatalf("result struct missing 'flagged' attr: %v", err)
	}
	list, ok := flaggedVal.(*starlark.List)
	if !ok {
		t.Fatalf("expected list 'flagged' attr, got %T", flaggedVal)
	}
	var flagged []string
	for i := 0; i < list.Len(); i++ {
		if s, ok := starlark.AsString(list.Index(i)); ok {
			flagged = append(flagged, s)
		}
	}
	return flagged
}

func fileMethodsFixture() []map[string]any {
	return []map[string]any{
		{
			"name":    "Copy",
			"returns": "(string, error)",
			"params": []map[string]any{
				{"name": "source", "type": "string"},
				{"name": "path", "type": "string"},
			},
		},
		{
			"name":    "Remove",
			"returns": "(bool, error)",
			"params": []map[string]any{
				{"name": "path", "type": "string"},
			},
		},
	}
}

func TestGeneratePlanReceiver(t *testing.T) {
	r := NewGoReceiver()
	desc := buildTestDescriptor(t, fileMethodsFixture())

	result := callMethod(t, r, "generate",
		starlark.Tuple{starlark.String(testPlanReceiverTemplate), desc}, nil)

	code := extractGeneratedCode(t, result)

	// Valid Go syntax
	if _, err := format.Source([]byte(code)); err != nil {
		t.Fatalf("generated code is not valid Go:\n%s\nerror: %v", code, err)
	}

	// Registration
	if !strings.Contains(code, "op.RegisterBinding") {
		t.Error("should register via op.RegisterBinding")
	}
	if !strings.Contains(code, `Name:     "file"`) {
		t.Error("binding should use provider name")
	}
	if !strings.Contains(code, "PlannedFactory") {
		t.Error("binding should set PlannedFactory")
	}

	// WrapPlanned constructor
	if !strings.Contains(code, "func NewFilePlan(") {
		t.Error("missing NewFilePlan constructor")
	}
	if !strings.Contains(code, `op.WrapPlanned("file"`) {
		t.Error("constructor should call op.WrapPlanned")
	}
	if !strings.Contains(code, "reflect.TypeOf((*Provider)(nil))") {
		t.Error("WrapPlanned should use reflect.TypeOf for provider")
	}
	if !strings.Contains(code, "Params") {
		t.Error("WrapPlanned should pass Params")
	}
}

func TestGenerateGraphActions(t *testing.T) {
	r := NewGoReceiver()
	desc := buildTestDescriptor(t, fileMethodsFixture())
	// Graph actions use per-provider package
	must(t, desc.SetKey(starlark.String("package"), starlark.String("file")))

	result := callMethod(t, r, "generate",
		starlark.Tuple{starlark.String(testGraphActionsTemplate), desc}, nil)

	code := extractGeneratedCode(t, result)

	// Valid Go syntax
	if _, err := format.Source([]byte(code)); err != nil {
		t.Fatalf("generated code is not valid Go:\n%s\nerror: %v", code, err)
	}

	// Registration
	if !strings.Contains(code, "op.RegisterBinding") {
		t.Error("should register via op.RegisterBinding")
	}
	if !strings.Contains(code, `Name: "file"`) {
		t.Error("binding should use provider name")
	}
	if !strings.Contains(code, "ActionRegistrar") {
		t.Error("binding should set ActionRegistrar")
	}

	// RegisterReflectedActions
	if !strings.Contains(code, `op.RegisterReflectedActions(reg, "file"`) {
		t.Error("should call RegisterReflectedActions with provider name")
	}
	if !strings.Contains(code, "&Provider{}") {
		t.Error("should pass &Provider{} to RegisterReflectedActions")
	}
	if !strings.Contains(code, "Params") {
		t.Error("should pass Params to RegisterReflectedActions")
	}
}

func TestGenerateGateFlagsBadReturn(t *testing.T) {
	r := NewGoReceiver()
	desc := buildTestDescriptor(t, []map[string]any{
		{
			"name":    "Check",
			"returns": "string",
			"params":  []map[string]any{},
		},
	})

	result := callMethod(t, r, "generate",
		starlark.Tuple{starlark.String(testPlanReceiverTemplate), desc}, nil)

	flagged := extractFlaggedMethods(t, result)
	if len(flagged) == 0 {
		t.Fatal("expected flagged methods for bad return signature")
	}
	found := false
	for _, f := range flagged {
		if strings.Contains(f, "expected (T, error)") {
			found = true
			break
		}
	}
	if !found {
		t.Errorf("flagged should mention expected format: %v", flagged)
	}
}

func TestGenerateVariadicParam(t *testing.T) {
	r := NewGoReceiver()
	desc := buildTestDescriptor(t, []map[string]any{
		{
			"name":    "Install",
			"returns": "(string, error)",
			"params": []map[string]any{
				{"name": "packages", "type": "string", "variadic": true},
			},
		},
	})

	result := callMethod(t, r, "generate",
		starlark.Tuple{starlark.String(testPlanReceiverTemplate), desc}, nil)

	code := extractGeneratedCode(t, result)

	// Valid Go syntax
	if _, err := format.Source([]byte(code)); err != nil {
		t.Fatalf("generated code is not valid Go:\n%s\nerror: %v", code, err)
	}

	// WrapPlanned constructor generated
	if !strings.Contains(code, "op.WrapPlanned") {
		t.Error("should use op.WrapPlanned")
	}

	// Variadic params pass through to reflection layer
	if !strings.Contains(code, "Params") {
		t.Error("should reference Params")
	}
}

func TestGoGenerateAttr(t *testing.T) {
	r := NewGoReceiver()

	// Check AttrNames includes "generate"
	names := r.AttrNames()
	found := false
	for _, n := range names {
		if n == "generate" {
			found = true
			break
		}
	}
	if !found {
		t.Error("AttrNames() should include 'generate'")
	}

	// Check Attr("generate") returns a builtin
	attr, err := r.Attr("generate")
	if err != nil {
		t.Fatalf("Attr(generate): %v", err)
	}
	if _, ok := attr.(*starlark.Builtin); !ok {
		t.Fatalf("Attr(generate) returned %T, want *starlark.Builtin", attr)
	}
}

func TestGoTemplateAttr(t *testing.T) {
	r := NewGoReceiver()

	// Check AttrNames includes "template"
	names := r.AttrNames()
	found := false
	for _, n := range names {
		if n == "template" {
			found = true
			break
		}
	}
	if !found {
		t.Error("AttrNames() should include 'template'")
	}

	// Check Attr("template") returns a builtin
	attr, err := r.Attr("template")
	if err != nil {
		t.Fatalf("Attr(template): %v", err)
	}
	if _, ok := attr.(*starlark.Builtin); !ok {
		t.Fatalf("Attr(template) returned %T, want *starlark.Builtin", attr)
	}
}

func TestGoTemplateReturnsContent(t *testing.T) {
	r := NewGoReceiver()

	result := callMethod(t, r, "template",
		starlark.Tuple{starlark.String("immediate_receiver")}, nil)

	content, ok := starlark.AsString(result)
	if !ok {
		t.Fatalf("expected string result, got %T", result)
	}

	if !strings.Contains(content, "{{.StructName}}{{.WrapperSuffix}}") {
		t.Error("template content should contain StructName+WrapperSuffix placeholder")
	}
	if !strings.Contains(content, "Code generated by go.generate") {
		t.Error("template content should contain generated header")
	}
}

func TestGoTemplateUnknownName(t *testing.T) {
	r := NewGoReceiver()
	thread := &starlark.Thread{Name: "test"}
	attr, _ := r.Attr("template")
	fn := attr.(*starlark.Builtin)
	_, err := fn.CallInternal(thread, starlark.Tuple{starlark.String("nonexistent")}, nil)
	if err == nil {
		t.Fatal("expected error for unknown template name")
	}
	if !strings.Contains(err.Error(), "unknown builtin") {
		t.Errorf("error should mention unknown builtin: %v", err)
	}
}

func TestGoMappingRoundTrip(t *testing.T) {
	r := NewGoReceiver()
	desc := buildTestDescriptor(t, []map[string]any{
		{
			"name":    "Link",
			"returns": "(string, error)",
			"params": []map[string]any{
				{"name": "source", "type": "string"},
				{"name": "path", "type": "string"},
			},
		},
		{
			"name":    "Copy",
			"returns": "(string, error)",
			"params": []map[string]any{
				{"name": "path", "type": "string"},
			},
		},
		{
			"name":    "Render",
			"returns": "(string, error)",
			"params": []map[string]any{
				{"name": "source", "type": "string"},
			},
		},
	})
	must(t, desc.SetKey(starlark.String("package"), starlark.String("execution")))
	must(t, desc.SetKey(starlark.String("namespace"), starlark.String("file")))
	must(t, desc.SetKey(starlark.String("impl_type"), starlark.String("fileOps")))

	result := callMethod(t, r, "mapping", starlark.Tuple{desc}, nil)

	yamlStr, ok := starlark.AsString(result)
	if !ok {
		t.Fatalf("expected string result, got %T", result)
	}

	// Parse the YAML output
	var mapping mappingFile
	if err := yaml.Unmarshal([]byte(yamlStr), &mapping); err != nil {
		t.Fatalf("failed to parse mapping YAML: %v\n%s", err, yamlStr)
	}

	// Verify top-level fields
	if mapping.Version != "1.0" {
		t.Errorf("expected version 1.0, got %q", mapping.Version)
	}
	if mapping.Struct != "fileOps" {
		t.Errorf("expected struct fileOps, got %q", mapping.Struct)
	}
	if mapping.Package != "execution" {
		t.Errorf("expected package execution, got %q", mapping.Package)
	}
	if mapping.Provider != "file" {
		t.Errorf("expected provider file, got %q", mapping.Provider)
	}

	// Verify operations
	if len(mapping.Operations) != 3 {
		t.Fatalf("expected 3 operations, got %d", len(mapping.Operations))
	}

	// Link
	link := mapping.Operations[0]
	if link.Name != "file.link" {
		t.Errorf("expected file.link, got %q", link.Name)
	}
	if link.GoMethod != "Link" {
		t.Errorf("expected GoMethod Link, got %q", link.GoMethod)
	}
	if len(link.Params) != 2 {
		t.Fatalf("expected 2 params, got %d", len(link.Params))
	}
	if link.Params[0].Name != "source" || link.Params[0].Type != "string" {
		t.Errorf("unexpected first param: %+v", link.Params[0])
	}

	// Copy
	copyOp := mapping.Operations[1]
	if copyOp.Name != "file.copy" {
		t.Errorf("expected file.copy, got %q", copyOp.Name)
	}
	if len(copyOp.Params) != 1 {
		t.Fatalf("expected 1 param, got %d", len(copyOp.Params))
	}

	// Render
	render := mapping.Operations[2]
	if render.Name != "file.render" {
		t.Errorf("expected file.render, got %q", render.Name)
	}

	// Verify header comment
	if !strings.Contains(yamlStr, "# Generated by go.mapping") {
		t.Error("missing header comment")
	}
}

func TestGoMappingAttr(t *testing.T) {
	r := NewGoReceiver()

	// Check AttrNames includes "mapping"
	names := r.AttrNames()
	found := false
	for _, n := range names {
		if n == "mapping" {
			found = true
			break
		}
	}
	if !found {
		t.Error("AttrNames() should include 'mapping'")
	}

	// Check Attr("mapping") returns a builtin
	attr, err := r.Attr("mapping")
	if err != nil {
		t.Fatalf("Attr(mapping): %v", err)
	}
	if _, ok := attr.(*starlark.Builtin); !ok {
		t.Fatalf("Attr(mapping) returned %T, want *starlark.Builtin", attr)
	}
}

func TestGoMappingFrameworkTypes(t *testing.T) {
	r := NewGoReceiver()
	desc := buildTestDescriptor(t, []map[string]any{
		{
			"name":    "Decrypt",
			"returns": "([]byte, error)",
			"params": []map[string]any{
				{"name": "decryptor", "type": "func(string, []byte) ([]byte, error)"},
				{"name": "source", "type": "string"},
				{"name": "content", "type": "[]byte"},
			},
		},
		{
			"name":    "Shell",
			"returns": "(bool, error)",
			"params": []map[string]any{
				{"name": "command", "type": "string"},
				{"name": "output", "type": "io.Writer"},
			},
		},
		{
			"name":    "Copy",
			"returns": "(string, error)",
			"params": []map[string]any{
				{"name": "path", "type": "string"},
				{"name": "mode", "type": "os.FileMode"},
				{"name": "content", "type": "[]byte"},
			},
		},
	})
	must(t, desc.SetKey(starlark.String("package"), starlark.String("execution")))
	must(t, desc.SetKey(starlark.String("impl_type"), starlark.String("EncryptionService")))

	result := callMethod(t, r, "mapping", starlark.Tuple{desc}, nil)

	yamlStr, ok := starlark.AsString(result)
	if !ok {
		t.Fatalf("expected string result, got %T", result)
	}

	// Parse the YAML output
	var mapping mappingFile
	if err := yaml.Unmarshal([]byte(yamlStr), &mapping); err != nil {
		t.Fatalf("failed to parse mapping YAML: %v\n%s", err, yamlStr)
	}

	if len(mapping.Operations) != 3 {
		t.Fatalf("expected 3 operations, got %d", len(mapping.Operations))
	}

	// Decrypt has framework params recorded
	decrypt := mapping.Operations[0]
	if decrypt.Name != "file.decrypt" {
		t.Errorf("expected file.decrypt, got %q", decrypt.Name)
	}
	if len(decrypt.Params) != 3 {
		t.Fatalf("expected 3 params, got %d", len(decrypt.Params))
	}
	if decrypt.Params[0].Type != "func(string, []byte) ([]byte, error)" {
		t.Errorf("expected func type, got %q", decrypt.Params[0].Type)
	}

	// Shell has bool return and io.Writer param
	shell := mapping.Operations[1]
	if shell.Name != "file.shell" {
		t.Errorf("expected file.shell, got %q", shell.Name)
	}
	if len(shell.Params) != 2 {
		t.Fatalf("expected 2 params, got %d", len(shell.Params))
	}
}

func TestGoMappingGateEnforcement(t *testing.T) {
	t.Run("unmapped type passes through", func(t *testing.T) {
		r := NewGoReceiver()
		desc := buildTestDescriptor(t, []map[string]any{
			{
				"name":    "Send",
				"returns": "(string, error)",
				"params": []map[string]any{
					{"name": "ch", "type": "chan string"},
				},
			},
		})

		// All types pass through — reflection handles coercion.
		result := callMethod(t, r, "mapping", starlark.Tuple{desc}, nil)
		yamlStr, ok := starlark.AsString(result)
		if !ok {
			t.Fatalf("expected string result, got %T", result)
		}
		var mapping mappingFile
		if err := yaml.Unmarshal([]byte(yamlStr), &mapping); err != nil {
			t.Fatalf("failed to parse mapping YAML: %v", err)
		}
		if len(mapping.Operations) != 1 {
			t.Errorf("expected 1 operation (all types pass through), got %d", len(mapping.Operations))
		}
	})

	t.Run("bad return", func(t *testing.T) {
		r := NewGoReceiver()
		desc := buildTestDescriptor(t, []map[string]any{
			{
				"name":    "Check",
				"returns": "string",
				"params":  []map[string]any{},
			},
		})

		thread := &starlark.Thread{Name: "test"}
		attr, _ := r.Attr("mapping")
		fn := attr.(*starlark.Builtin)
		_, err := fn.CallInternal(thread, starlark.Tuple{desc}, nil)
		if err == nil {
			t.Fatal("expected error for bad return signature")
		}
		if !strings.Contains(err.Error(), "expected (T, error)") {
			t.Errorf("error should mention return format: %v", err)
		}
	})
}

func TestInferContentModel(t *testing.T) {
	tests := []struct {
		name      string
		valueType string
		params    []paramInfo
		want      string
	}{
		{
			name:      "error-only return",
			valueType: "",
			params:    []paramInfo{{GoType: "[]byte"}},
			want:      "none",
		},
		{
			name:      "string return with []byte last param",
			valueType: "string",
			params: []paramInfo{
				{GoType: "string"},
				{GoType: "[]byte"},
			},
			want: "consumer",
		},
		{
			name:      "[]byte return with []byte last param",
			valueType: "[]byte",
			params: []paramInfo{
				{GoType: "string"},
				{GoType: "[]byte"},
			},
			want: "transformer",
		},
		{
			name:      "string return without []byte last param",
			valueType: "string",
			params: []paramInfo{
				{GoType: "string"},
			},
			want: "none",
		},
		{
			name:      "no params",
			valueType: "string",
			params:    nil,
			want:      "none",
		},
		{
			name:      "bool return with []byte last param",
			valueType: "bool",
			params: []paramInfo{
				{GoType: "[]byte"},
			},
			want: "none",
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := inferContentModel(tc.valueType, tc.params)
			if got != tc.want {
				t.Errorf("inferContentModel(%q, ...) = %q, want %q", tc.valueType, got, tc.want)
			}
		})
	}
}

func TestValidateCompensableReturn(t *testing.T) {
	tests := []struct {
		input     string
		wantValue string
		wantErr   bool
	}{
		// Valid: (T, U, error)
		{"(string, map[string]any, error)", "string", false},
		{"([]byte, map[string]any, error)", "[]byte", false},
		{"(bool, int, error)", "bool", false},
		{"(int, int, error)", "int", false},
		{"(int, any, error)", "int", false},
		// Invalid: missing Result or UndoState
		{"(map[string]any, error)", "", true},
		{"(string, error)", "", true},
		{"(int, error)", "", true},
		// Invalid: wrong shape
		{"error", "", true},
		{"", "", true},
		{"string", "", true},
		{"(map[string]any)", "", true},
		{"(, map[string]any, error)", "", true},
		{"(int, int, int, error)", "", true},
	}
	for _, tc := range tests {
		t.Run(tc.input, func(t *testing.T) {
			got, _, err := validateCompensableReturn(tc.input)
			if tc.wantErr {
				if err == nil {
					t.Errorf("expected error for %q, got value %q", tc.input, got)
				}
			} else {
				if err != nil {
					t.Errorf("unexpected error for %q: %v", tc.input, err)
				}
				if got != tc.wantValue {
					t.Errorf("validateCompensableReturn(%q) = %q, want %q", tc.input, got, tc.wantValue)
				}
			}
		})
	}
}

func TestGenerateSignatureErrors(t *testing.T) {
	generateFlagged := func(t *testing.T, methods []map[string]any) []string {
		t.Helper()
		r := NewGoReceiver()
		desc := buildTestDescriptor(t, methods)
		must(t, desc.SetKey(starlark.String("package"), starlark.String("file")))
		must(t, desc.SetKey(starlark.String("impl_type"), starlark.String("Provider")))
		result := callMethod(t, r, "generate",
			starlark.Tuple{starlark.String(testGraphActionsTemplate), desc}, nil)
		return extractFlaggedMethods(t, result)
	}

	t.Run("error only", func(t *testing.T) {
		flagged := generateFlagged(t, []map[string]any{
			{
				"name":    "Remove",
				"returns": "error",
				"params": []map[string]any{
					{"name": "path", "type": "string"},
				},
			},
		})
		if len(flagged) == 0 {
			t.Fatal("expected flagged method for error-only return")
		}
		if !strings.Contains(flagged[0], "every method must return a Result") {
			t.Errorf("should say every method must return a Result, got: %v", flagged)
		}
	})

	t.Run("no return value", func(t *testing.T) {
		flagged := generateFlagged(t, []map[string]any{
			{
				"name":    "Noop",
				"returns": "",
				"params":  []map[string]any{},
			},
		})
		if len(flagged) == 0 {
			t.Fatal("expected flagged method for no return value")
		}
		if !strings.Contains(flagged[0], "got no return value") {
			t.Errorf("should say got no return value, got: %v", flagged)
		}
	})

	t.Run("too many return values", func(t *testing.T) {
		flagged := generateFlagged(t, []map[string]any{
			{
				"name":    "Bad",
				"returns": "(int, int, int, error)",
				"params":  []map[string]any{},
			},
		})
		if len(flagged) == 0 {
			t.Fatal("expected flagged method for too many return values")
		}
		if !strings.Contains(flagged[0], "too many return values") {
			t.Errorf("should say too many return values, got: %v", flagged)
		}
	})
}

func TestMethodLocationInErrors(t *testing.T) {
	t.Run("with file and line", func(t *testing.T) {
		m := methodInfo{GoName: "Link", File: "provider.go", Line: 42}
		loc := methodLocation(m)
		if loc != "provider.go:42: Link" {
			t.Errorf("expected 'provider.go:42: Link', got %q", loc)
		}
	})

	t.Run("without file", func(t *testing.T) {
		m := methodInfo{GoName: "Link"}
		loc := methodLocation(m)
		if loc != "Link" {
			t.Errorf("expected 'Link', got %q", loc)
		}
	})

	t.Run("file only no line", func(t *testing.T) {
		m := methodInfo{GoName: "Link", File: "provider.go"}
		loc := methodLocation(m)
		if loc != "Link" {
			t.Errorf("expected fallback to 'Link' when line is 0, got %q", loc)
		}
	})
}

// =============================================================================
// PHASE 4: NEW CONVERSION TYPES
// =============================================================================

func TestValidateImmediateReturn(t *testing.T) {
	tests := []struct {
		input          string
		wantValue      string
		wantHasErr     bool
		wantCompensable bool
		wantErr        bool
	}{
		// Void
		{"", "", false, false, false},
		// Error-only
		{"error", "", true, false, false},
		// Bare type (no error)
		{"string", "string", false, false, false},
		{"bool", "bool", false, false, false},
		{"[]string", "[]string", false, false, false},
		// Standard (T, error) — non-compensable
		{"(string, error)", "string", true, false, false},
		{"([]byte, error)", "[]byte", true, false, false},
		// Compensable (T, U, error) — inferred
		{"(string, map[string]any, error)", "string", true, true, false},
	}
	for _, tc := range tests {
		name := tc.input
		if name == "" {
			name = "(empty)"
		}
		t.Run(name, func(t *testing.T) {
			valueType, hasError, compensable, err := validateImmediateReturn(tc.input)
			if tc.wantErr {
				if err == nil {
					t.Errorf("expected error for %q, got valueType=%q hasError=%v compensable=%v", tc.input, valueType, hasError, compensable)
				}
				return
			}
			if err != nil {
				t.Errorf("unexpected error for %q: %v", tc.input, err)
				return
			}
			if valueType != tc.wantValue {
				t.Errorf("valueType = %q, want %q", valueType, tc.wantValue)
			}
			if hasError != tc.wantHasErr {
				t.Errorf("hasError = %v, want %v", hasError, tc.wantHasErr)
			}
			if compensable != tc.wantCompensable {
				t.Errorf("compensable = %v, want %v", compensable, tc.wantCompensable)
			}
		})
	}
}


// buildCallableParam creates a callable param dict for testing.
func buildCallableParam(t *testing.T, name, goType, role string) starlark.Value {
	t.Helper()
	d := starlark.NewDict(3)
	must(t, d.SetKey(starlark.String("go_name"), starlark.String(name)))
	must(t, d.SetKey(starlark.String("go_type"), starlark.String(goType)))
	must(t, d.SetKey(starlark.String("role"), starlark.String(role)))
	return d
}

// buildParamDict creates a simple param dict for testing.
func buildParamDict(t *testing.T, name, goType string) starlark.Value {
	t.Helper()
	d := starlark.NewDict(3)
	must(t, d.SetKey(starlark.String("name"), starlark.String(name)))
	must(t, d.SetKey(starlark.String("type"), starlark.String(goType)))
	must(t, d.SetKey(starlark.String("variadic"), starlark.Bool(false)))
	return d
}

// =============================================================================
// GATE 3: COMPENSATE METHOD VALIDATION
// =============================================================================

func TestGenerateGateRejectsMissingCompensateMethod(t *testing.T) {
	r := NewGoReceiver()
	desc := buildTestDescriptor(t, []map[string]any{
		{
			"name":    "Install",
			"returns": "(any, map[string]any, error)",
			"params": []map[string]any{
				{"name": "name", "type": "string"},
			},
		},
	})
	must(t, desc.SetKey(starlark.String("package"), starlark.String("pkg")))
	must(t, desc.SetKey(starlark.String("impl_type"), starlark.String("Provider")))
	// Provide all_methods WITHOUT CompensateInstall
	allMethods := starlark.NewList([]starlark.Value{
		starlark.String("Install"),
		starlark.String("Remove"),
	})
	must(t, desc.SetKey(starlark.String("all_methods"), allMethods))

	thread := &starlark.Thread{Name: "test"}
	attr, _ := r.Attr("generate")
	fn := attr.(*starlark.Builtin)
	_, err := fn.CallInternal(thread, starlark.Tuple{starlark.String(testGraphActionsTemplate), desc}, nil)
	if err == nil {
		t.Fatal("expected error for compensable method without CompensateInstall")
	}
	if !strings.Contains(err.Error(), "CompensateInstall") {
		t.Errorf("error should mention CompensateInstall, got: %v", err)
	}
	if !strings.Contains(err.Error(), "compensable return signature requires") {
		t.Errorf("error should mention compensable return signature, got: %v", err)
	}
}

func TestGenerateGateRejectsEmptyAllMethods(t *testing.T) {
	// Compensable methods require all_methods — no exceptions.
	r := NewGoReceiver()
	desc := buildTestDescriptor(t, []map[string]any{
		{
			"name":    "Install",
			"returns": "(any, map[string]any, error)",
			"params": []map[string]any{
				{"name": "name", "type": "string"},
			},
		},
	})
	must(t, desc.SetKey(starlark.String("package"), starlark.String("pkg")))
	must(t, desc.SetKey(starlark.String("impl_type"), starlark.String("Provider")))
	// No all_methods set — Gate 3 rejects

	thread := &starlark.Thread{Name: "test"}
	attr, _ := r.Attr("generate")
	fn := attr.(*starlark.Builtin)
	_, err := fn.CallInternal(thread, starlark.Tuple{starlark.String(testGraphActionsTemplate), desc}, nil)
	if err == nil {
		t.Fatal("expected error for compensable method without all_methods")
	}
	if !strings.Contains(err.Error(), "all_methods is empty") {
		t.Errorf("error should mention all_methods is empty, got: %v", err)
	}
}

// =============================================================================
// TESTS FOR NEW CODEGEN FEATURES (optional params, custom returns, struct params)
// =============================================================================

func TestProviderFieldFromValue(t *testing.T) {
	d := starlark.NewDict(4)
	must(t, d.SetKey(starlark.String("go_name"), starlark.String("Root")))
	must(t, d.SetKey(starlark.String("cfg_field"), starlark.String("WorkDir")))
	must(t, d.SetKey(starlark.String("default"), starlark.String(`"."`)))
	must(t, d.SetKey(starlark.String("zero_value"), starlark.String(`""`)))

	pf, err := providerFieldFromValue(d)
	if err != nil {
		t.Fatalf("providerFieldFromValue: %v", err)
	}
	if pf.GoName != "Root" {
		t.Errorf("GoName = %q, want %q", pf.GoName, "Root")
	}
	if pf.CfgField != "WorkDir" {
		t.Errorf("CfgField = %q, want %q", pf.CfgField, "WorkDir")
	}
	if pf.Default != `"."` {
		t.Errorf("Default = %q, want %q", pf.Default, `"."`)
	}
	if pf.ZeroValue != `""` {
		t.Errorf("ZeroValue = %q, want %q", pf.ZeroValue, `""`)
	}
}

func TestParamInfoFromValueOptional(t *testing.T) {
	d := starlark.NewDict(6)
	must(t, d.SetKey(starlark.String("name"), starlark.String("gitignore")))
	must(t, d.SetKey(starlark.String("type"), starlark.String("bool")))
	must(t, d.SetKey(starlark.String("variadic"), starlark.Bool(false)))
	must(t, d.SetKey(starlark.String("optional"), starlark.Bool(true)))
	must(t, d.SetKey(starlark.String("default"), starlark.String("true")))
	must(t, d.SetKey(starlark.String("struct_type"), starlark.String("SomeStruct")))

	p, err := paramInfoFromValue(d)
	if err != nil {
		t.Fatalf("paramInfoFromValue: %v", err)
	}
	if !p.Optional {
		t.Error("Optional should be true")
	}
	if p.Default != "true" {
		t.Errorf("Default = %q, want %q", p.Default, "true")
	}
	if p.StructType != "SomeStruct" {
		t.Errorf("StructType = %q, want %q", p.StructType, "SomeStruct")
	}
}

func TestDescriptorFromValueRegistered(t *testing.T) {
	desc := buildTestDescriptor(t, fileMethodsFixture())
	must(t, desc.SetKey(starlark.String("registered"), starlark.Bool(true)))
	must(t, desc.SetKey(starlark.String("provider_import"), starlark.String("github.com/example/pkg")))

	// Build provider fields list
	pf := starlark.NewDict(4)
	must(t, pf.SetKey(starlark.String("go_name"), starlark.String("Root")))
	must(t, pf.SetKey(starlark.String("cfg_field"), starlark.String("WorkDir")))
	must(t, pf.SetKey(starlark.String("default"), starlark.String(`"."`)))
	must(t, pf.SetKey(starlark.String("zero_value"), starlark.String(`""`)))
	pfList := starlark.NewList([]starlark.Value{pf})
	must(t, desc.SetKey(starlark.String("provider_fields"), pfList))

	result, err := descriptorFromValue("immediate_receiver", desc)
	if err != nil {
		t.Fatalf("descriptorFromValue: %v", err)
	}
	if !result.Registered {
		t.Error("Registered should be true")
	}
	if result.ProviderImport != "github.com/example/pkg" {
		t.Errorf("ProviderImport = %q, want %q", result.ProviderImport, "github.com/example/pkg")
	}
	if len(result.ProviderFields) != 1 {
		t.Fatalf("ProviderFields length = %d, want 1", len(result.ProviderFields))
	}
	if result.ProviderFields[0].GoName != "Root" {
		t.Errorf("ProviderFields[0].GoName = %q, want %q", result.ProviderFields[0].GoName, "Root")
	}
}

// =============================================================================
// STRUCT CONVERTER TESTS
// =============================================================================

func TestConverterFuncSimpleStruct(t *testing.T) {
	c := converterInfo{
		FuncName:     "statsToStarlark",
		GoType:       "Stats",
		IsPointer:    true,
		StarlarkName: "stats",
		Fields: []converterFieldInfo{
			{GoName: "Path", SnakeName: "path", Kind: "string"},
			{GoName: "LOC", SnakeName: "loc", Kind: "int"},
			{GoName: "Bytes", SnakeName: "bytes", Kind: "int64"},
			{GoName: "Active", SnakeName: "active", Kind: "bool"},
		},
	}

	code := templateFuncConverterFunc(c, "provider.")
	if !strings.Contains(code, "func statsToStarlark(v *provider.Stats)") {
		t.Error("missing function signature")
	}
	if !strings.Contains(code, `starlark.String(v.Path)`) {
		t.Error("missing string conversion")
	}
	if !strings.Contains(code, `starlark.MakeInt(v.LOC)`) {
		t.Error("missing int conversion")
	}
	if !strings.Contains(code, `starlark.MakeInt64(v.Bytes)`) {
		t.Error("missing int64 conversion")
	}
	if !strings.Contains(code, `starlark.Bool(v.Active)`) {
		t.Error("missing bool conversion")
	}
}

func TestConverterFuncStructSlice(t *testing.T) {
	c := converterInfo{
		FuncName:     "indexToStarlark",
		GoType:       "Index",
		IsPointer:    true,
		StarlarkName: "index",
		Fields: []converterFieldInfo{
			{GoName: "Files", SnakeName: "files", Kind: "struct_slice", Converter: "indexedFileToStarlark"},
		},
	}

	code := templateFuncConverterFunc(c, "provider.")
	if !strings.Contains(code, "filesList := make([]starlark.Value, len(v.Files))") {
		t.Error("missing pre-loop slice allocation")
	}
	if !strings.Contains(code, "filesList[i] = indexedFileToStarlark(filesItem)") {
		t.Error("missing converter call in loop")
	}
	if !strings.Contains(code, `starlark.NewList(filesList)`) {
		t.Error("missing NewList for slice field")
	}
}

func TestConverterFuncInlineStruct(t *testing.T) {
	c := converterInfo{
		FuncName:     "statsToStarlark",
		GoType:       "Stats",
		IsPointer:    true,
		StarlarkName: "stats",
		Fields: []converterFieldInfo{
			{
				GoName: "Totals", SnakeName: "totals", Kind: "inline_struct",
				InlineName: "totals",
				InlineFields: []converterFieldInfo{
					{GoName: "FileCount", SnakeName: "file_count", Kind: "int"},
					{GoName: "TotalBytes", SnakeName: "total_bytes", Kind: "int64"},
				},
			},
		},
	}

	code := templateFuncConverterFunc(c, "")
	if !strings.Contains(code, `starlarkstruct.FromStringDict(starlark.String("totals")`) {
		t.Error("missing inline struct construction")
	}
	if !strings.Contains(code, `starlark.MakeInt(v.Totals.FileCount)`) {
		t.Error("missing inline field access")
	}
}

func TestConverterFuncNullablePtr(t *testing.T) {
	c := converterInfo{
		FuncName:     "reportToStarlark",
		GoType:       "Report",
		IsPointer:    true,
		StarlarkName: "report",
		Fields: []converterFieldInfo{
			{GoName: "Stats", SnakeName: "stats", Kind: "struct_ptr", Converter: "statsToStarlark"},
			{GoName: "Index", SnakeName: "index", Kind: "struct_ptr", Converter: "indexToStarlark", Nullable: true},
		},
	}

	code := templateFuncConverterFunc(c, "")
	// Non-nullable struct_ptr should be a static field
	if !strings.Contains(code, `statsToStarlark(v.Stats)`) {
		t.Error("missing non-nullable struct_ptr converter call")
	}
	// Nullable should use if/else pattern
	if !strings.Contains(code, "if v.Index != nil") {
		t.Error("missing nil check for nullable field")
	}
	if !strings.Contains(code, `indexToStarlark(v.Index)`) {
		t.Error("missing converter call in nil check")
	}
	if !strings.Contains(code, "starlark.None") {
		t.Error("missing None for nil case")
	}
}

func TestConverterFuncConditionalField(t *testing.T) {
	c := converterInfo{
		FuncName:     "funcToStarlark",
		GoType:       "IndexedFunction",
		IsPointer:    false,
		StarlarkName: "function",
		Fields: []converterFieldInfo{
			{GoName: "Name", SnakeName: "name", Kind: "string"},
			{GoName: "Docstring", SnakeName: "docstring", Kind: "conditional", Guard: "HasDocstring", GuardField: "Docstring", GuardKind: "string"},
		},
	}

	code := templateFuncConverterFunc(c, "")
	if !strings.Contains(code, "if v.HasDocstring") {
		t.Error("missing conditional guard check")
	}
	if !strings.Contains(code, `starlark.String(v.Docstring)`) {
		t.Error("missing true-case expression")
	}
}

func TestConverterFuncInlineSliceWithConditional(t *testing.T) {
	c := converterInfo{
		FuncName:     "fileToStarlark",
		GoType:       "IndexedFile",
		IsPointer:    false,
		StarlarkName: "file",
		Fields: []converterFieldInfo{
			{GoName: "Path", SnakeName: "path", Kind: "string"},
			{
				GoName: "Functions", SnakeName: "functions", Kind: "struct_slice",
				InlineName: "function",
				InlineFields: []converterFieldInfo{
					{GoName: "Name", SnakeName: "name", Kind: "string"},
					{GoName: "Line", SnakeName: "line", Kind: "int"},
					{GoName: "Docstring", SnakeName: "docstring", Kind: "conditional", Guard: "HasDocstring", GuardField: "Docstring", GuardKind: "string"},
				},
			},
		},
	}

	code := templateFuncConverterFunc(c, "")
	// Pre-loop for inline struct_slice
	if !strings.Contains(code, "functionsList := make([]starlark.Value") {
		t.Error("missing pre-loop for inline slice")
	}
	// Inline loop should use dynamic dict due to conditional
	if !strings.Contains(code, "if functionsItem.HasDocstring") {
		t.Error("missing conditional in inline loop body")
	}
}

func TestConverterFuncNullableSlice(t *testing.T) {
	c := converterInfo{
		FuncName:     "reportToStarlark",
		GoType:       "Report",
		IsPointer:    true,
		StarlarkName: "report",
		Fields: []converterFieldInfo{
			{
				GoName: "Hotspots", SnakeName: "hotspots", Kind: "struct_slice",
				Nullable: true, NilExpr: "starlark.NewList(nil)",
				InlineName: "hotspot",
				InlineFields: []converterFieldInfo{
					{GoName: "File", SnakeName: "file", Kind: "string"},
					{GoName: "Line", SnakeName: "line", Kind: "int"},
				},
			},
		},
	}

	code := templateFuncConverterFunc(c, "")
	if !strings.Contains(code, "if v.Hotspots != nil") {
		t.Error("missing nil check for nullable slice")
	}
	if !strings.Contains(code, "starlark.NewList(nil)") {
		t.Error("missing nil expr for null case")
	}
}

func TestConverterFuncStringSlice(t *testing.T) {
	c := converterInfo{
		FuncName:     "loadToStarlark",
		GoType:       "Load",
		IsPointer:    false,
		StarlarkName: "load",
		Fields: []converterFieldInfo{
			{GoName: "Module", SnakeName: "module", Kind: "string"},
			{GoName: "Names", SnakeName: "names", Kind: "string_slice"},
		},
	}

	code := templateFuncConverterFunc(c, "")
	if !strings.Contains(code, "op.StringSliceToList(v.Names)") {
		t.Error("missing string_slice conversion")
	}
}

func TestNeedsOpImport(t *testing.T) {
	withOp := []converterInfo{
		{Fields: []converterFieldInfo{{Kind: "string_slice"}}},
	}
	if !templateFuncNeedsOpImport(withOp) {
		t.Error("should need op import for string_slice")
	}

	// Nested string_slice
	nested := []converterInfo{
		{Fields: []converterFieldInfo{
			{Kind: "struct_slice", InlineFields: []converterFieldInfo{{Kind: "string_slice"}}},
		}},
	}
	if !templateFuncNeedsOpImport(nested) {
		t.Error("should need op import for nested string_slice")
	}

	withoutOp := []converterInfo{
		{Fields: []converterFieldInfo{{Kind: "string"}, {Kind: "int"}}},
	}
	if templateFuncNeedsOpImport(withoutOp) {
		t.Error("should not need op import without string_slice")
	}
}

func TestGenerateStructConverter(t *testing.T) {
	r := NewGoReceiver()

	// Build a converter descriptor
	desc := starlark.NewDict(5)
	must(t, desc.SetKey(starlark.String("package"), starlark.String("starlarkcode")))
	must(t, desc.SetKey(starlark.String("provider"), starlark.String("starlarkcode")))
	must(t, desc.SetKey(starlark.String("struct_name"), starlark.String("Starlarkcode")))
	must(t, desc.SetKey(starlark.String("namespace"), starlark.String("starlarkcode")))
	must(t, desc.SetKey(starlark.String("provider_import"), starlark.String("github.com/NobleFactor/devlore-cli/pkg/op/provider/starlarkcode")))

	// Build a simple converter
	field1 := starlark.NewDict(3)
	must(t, field1.SetKey(starlark.String("go_name"), starlark.String("Path")))
	must(t, field1.SetKey(starlark.String("snake_name"), starlark.String("path")))
	must(t, field1.SetKey(starlark.String("kind"), starlark.String("string")))

	field2 := starlark.NewDict(3)
	must(t, field2.SetKey(starlark.String("go_name"), starlark.String("LOC")))
	must(t, field2.SetKey(starlark.String("snake_name"), starlark.String("loc")))
	must(t, field2.SetKey(starlark.String("kind"), starlark.String("int")))

	conv := starlark.NewDict(5)
	must(t, conv.SetKey(starlark.String("func_name"), starlark.String("fileStatsToStarlark")))
	must(t, conv.SetKey(starlark.String("go_type"), starlark.String("FileStats")))
	must(t, conv.SetKey(starlark.String("is_pointer"), starlark.Bool(false)))
	must(t, conv.SetKey(starlark.String("starlark_name"), starlark.String("file_stats")))
	must(t, conv.SetKey(starlark.String("fields"), starlark.NewList([]starlark.Value{field1, field2})))

	must(t, desc.SetKey(starlark.String("converters"), starlark.NewList([]starlark.Value{conv})))

	result := callMethod(t, r, "generate",
		starlark.Tuple{starlark.String("struct_converter"), desc}, nil)

	code := extractGeneratedCode(t, result)

	// Valid Go syntax
	if _, err := format.Source([]byte(code)); err != nil {
		t.Fatalf("generated code is not valid Go:\n%s\nerror: %v", code, err)
	}

	if !strings.Contains(code, "func fileStatsToStarlark(v provider.FileStats)") {
		t.Error("missing converter function signature with provider prefix")
	}
	if !strings.Contains(code, `starlark.String(v.Path)`) {
		t.Error("missing string conversion")
	}
	if !strings.Contains(code, `starlark.MakeInt(v.LOC)`) {
		t.Error("missing int conversion")
	}
}


