// SPDX-License-Identifier: MIT
// Copyright Noble Factor. All rights reserved.

package starlark

import (
	"go/format"
	"strings"
	"testing"

	"go.starlark.net/starlark"
	"gopkg.in/yaml.v3"
)

// testPlanReceiverTemplate is the plan_receiver template content, kept as a
// test-local constant after the template was removed from production code.
// Production callers (devlore-cli) load it from a .go.tmpl file instead.
const testPlanReceiverTemplate = `// Code generated by go.generate; DO NOT EDIT.

package {{.Package}}

import (
	"fmt"

	"go.starlark.net/starlark"

	"github.com/NobleFactor/devlore-cli/internal/execution"
	"github.com/NobleFactor/devlore-cli/internal/host"
)

type {{.StructName}}Plan struct {
	Receiver
	graph   *execution.Graph
	host    host.Host
	project string
	reg     *execution.ActionRegistry
}

func New{{.StructName}}Plan(graph *execution.Graph, h host.Host, project string, reg *execution.ActionRegistry) *{{.StructName}}Plan {
	return &{{.StructName}}Plan{
		Receiver: NewReceiver("{{.Namespace}}"),
		graph:    graph,
		host:     h,
		project:  project,
		reg:      reg,
	}
}

func (p *{{.StructName}}Plan) Attr(name string) (starlark.Value, error) {
	switch name {
{{- range .Methods}}
	case "{{.SnakeName}}":
		return MakeAttr("{{$.Namespace}}.{{.SnakeName}}", p.{{.SnakeName}}), nil
{{- end}}
	default:
		return nil, NoSuchAttrError("{{.Namespace}}", name)
	}
}

func (p *{{.StructName}}Plan) AttrNames() []string {
	return []string{{"{"}}{{attrNamesList .Methods}}{{"}"}}
}
{{range .Methods}}
func (p *{{$.StructName}}Plan) {{.SnakeName}}(_ *starlark.Thread, _ *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
{{planUnpackArgs .}}

	node := &execution.Node{
		ID:      generateNodeID("{{$.Category}}-{{.SnakeName}}"),
		Action:  p.reg.MustGet("{{$.Category}}.{{.SnakeName}}"),
		Project: p.project,
	}
{{planFillSlots .}}

	p.graph.Nodes = append(p.graph.Nodes, node)
	return NewOutput(node, p.graph, ""), nil
}
{{end}}`

// testGraphActionsTemplate is the graph_actions template content, kept as a
// test-local constant after the template was removed from production code.
// Production callers (devlore-cli) load it from a .go.tmpl file instead.
const testGraphActionsTemplate = `// Code generated by go.generate; DO NOT EDIT.

package {{.Package}}

import (
	"fmt"

	"github.com/NobleFactor/devlore-cli/internal/execution"
)
{{range .Methods}}
// {{.GoName}} — {{.Doc}}
type {{.GoName}} struct{ Impl *Provider }

func (o *{{.GoName}}) Name() string { return "{{$.Category}}.{{.SnakeName}}" }

func (o *{{.GoName}}) Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error) {
{{graphReaders .}}

	if ctx.DryRun {
		_, _ = fmt.Fprintf(ctx.Logger, "[dry-run] {{$.Category}}.{{.SnakeName}} {{dryRunFmt .}}\n"{{dryRunVars .}}){{dryRunChecksum .}}
		return nil, nil, nil
	}
{{graphReturn . $.ImplType}}
}

{{graphUndo .}}
{{end}}
// Register registers all {{.Category}} actions with the given registry.
func Register(reg *execution.ActionRegistry) {
	p := &Provider{}
{{- range .Methods}}
	reg.Register(&{{.GoName}}{Impl: p})
{{- end}}
}
`

func TestCamelToSnake(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{"Copy", "copy"},
		{"WalkTree", "walk_tree"},
		{"ConfigGet", "config_get"},
		{"HTMLParser", "html_parser"},
		{"ID", "id"},
		{"HTTPSProxy", "https_proxy"},
		{"A", "a"},
		{"ABC", "abc"},
	}
	for _, tc := range tests {
		t.Run(tc.input, func(t *testing.T) {
			got := camelToSnake(tc.input)
			if got != tc.want {
				t.Errorf("camelToSnake(%q) = %q, want %q", tc.input, got, tc.want)
			}
		})
	}
}

func TestValidateReturnSignature(t *testing.T) {
	tests := []struct {
		input   string
		want    string
		wantErr bool
	}{
		{"(string, error)", "string", false},
		{"(bool, error)", "bool", false},
		{"(int, error)", "int", false},
		{"([]string, error)", "[]string", false},
		{"([]byte, error)", "[]byte", false},
		{"error", "", false}, // plain error return — no value type
		{"string", "", true},
		{"(string, int, error)", "", true},
		{"", "", true},
		{"(error)", "", true},
	}
	for _, tc := range tests {
		t.Run(tc.input, func(t *testing.T) {
			got, err := validateReturnSignature(tc.input)
			if tc.wantErr {
				if err == nil {
					t.Errorf("expected error for %q, got value %q", tc.input, got)
				}
			} else {
				if err != nil {
					t.Errorf("unexpected error for %q: %v", tc.input, err)
				}
				if got != tc.want {
					t.Errorf("validateReturnSignature(%q) = %q, want %q", tc.input, got, tc.want)
				}
			}
		})
	}
}

func TestValidateParamTypes(t *testing.T) {
	t.Run("valid", func(t *testing.T) {
		params := []paramInfo{
			{GoName: "source", GoType: "string"},
			{GoName: "count", GoType: "int"},
			{GoName: "verbose", GoType: "bool"},
			{GoName: "items", GoType: "[]string"},
		}
		if err := validateParamTypes(params); err != nil {
			t.Errorf("unexpected error: %v", err)
		}
	})

	t.Run("framework types", func(t *testing.T) {
		params := []paramInfo{
			{GoName: "content", GoType: "[]byte"},
			{GoName: "output", GoType: "io.Writer"},
			{GoName: "decryptor", GoType: "func(string, []byte) ([]byte, error)"},
			{GoName: "gitMv", GoType: "func(string, string) error"},
			{GoName: "mode", GoType: "os.FileMode"},
			{GoName: "data", GoType: "map[string]any"},
		}
		if err := validateParamTypes(params); err != nil {
			t.Errorf("unexpected error: %v", err)
		}
	})

	t.Run("invalid", func(t *testing.T) {
		params := []paramInfo{
			{GoName: "ch", GoType: "chan string"},
			{GoName: "fn", GoType: "func()"},
			{GoName: "node", GoType: "*Node"},
		}
		err := validateParamTypes(params)
		if err == nil {
			t.Fatal("expected error for unmapped types")
		}
		if !strings.Contains(err.Error(), "chan string") {
			t.Errorf("error should mention 'chan string': %v", err)
		}
		if !strings.Contains(err.Error(), "func()") {
			t.Errorf("error should mention 'func()': %v", err)
		}
		if !strings.Contains(err.Error(), "*Node") {
			t.Errorf("error should mention '*Node': %v", err)
		}
	})

	t.Run("mixed", func(t *testing.T) {
		params := []paramInfo{
			{GoName: "source", GoType: "string"},
			{GoName: "ch", GoType: "chan string"},
			{GoName: "count", GoType: "int"},
		}
		err := validateParamTypes(params)
		if err == nil {
			t.Fatal("expected error for mixed valid/invalid")
		}
		if !strings.Contains(err.Error(), "chan string") {
			t.Errorf("error should mention 'chan string': %v", err)
		}
	})
}

// buildTestDescriptor creates a Starlark dict descriptor for testing.
func buildTestDescriptor(t *testing.T, methods []map[string]any) *starlark.Dict {
	t.Helper()
	desc := starlark.NewDict(5)
	must(t, desc.SetKey(starlark.String("package"), starlark.String("starlark")))
	must(t, desc.SetKey(starlark.String("category"), starlark.String("file")))
	must(t, desc.SetKey(starlark.String("struct_name"), starlark.String("File")))
	must(t, desc.SetKey(starlark.String("namespace"), starlark.String("plan.file")))

	var methodsList []starlark.Value
	for _, m := range methods {
		md := starlark.NewDict(4)
		must(t, md.SetKey(starlark.String("name"), starlark.String(m["name"].(string))))
		must(t, md.SetKey(starlark.String("returns"), starlark.String(m["returns"].(string))))
		must(t, md.SetKey(starlark.String("doc"), starlark.String("")))

		if compensable, ok := m["compensable"].(bool); ok {
			must(t, md.SetKey(starlark.String("compensable"), starlark.Bool(compensable)))
		}

		var paramsList []starlark.Value
		if params, ok := m["params"].([]map[string]any); ok {
			for _, p := range params {
				pd := starlark.NewDict(3)
				must(t, pd.SetKey(starlark.String("name"), starlark.String(p["name"].(string))))
				must(t, pd.SetKey(starlark.String("type"), starlark.String(p["type"].(string))))
				variadic := false
				if v, ok := p["variadic"].(bool); ok {
					variadic = v
				}
				must(t, pd.SetKey(starlark.String("variadic"), starlark.Bool(variadic)))
				paramsList = append(paramsList, pd)
			}
		}
		must(t, md.SetKey(starlark.String("params"), starlark.NewList(paramsList)))
		methodsList = append(methodsList, md)
	}
	must(t, desc.SetKey(starlark.String("methods"), starlark.NewList(methodsList)))
	return desc
}

func must(t *testing.T, err error) {
	t.Helper()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func fileMethodsFixture() []map[string]any {
	return []map[string]any{
		{
			"name":    "Copy",
			"returns": "(string, error)",
			"params": []map[string]any{
				{"name": "source", "type": "string"},
				{"name": "path", "type": "string"},
			},
		},
		{
			"name":    "Remove",
			"returns": "(bool, error)",
			"params": []map[string]any{
				{"name": "path", "type": "string"},
			},
		},
	}
}

func TestGeneratePlanReceiver(t *testing.T) {
	r := NewGoReceiver()
	desc := buildTestDescriptor(t, fileMethodsFixture())

	result := callMethod(t, r, "generate",
		starlark.Tuple{starlark.String(testPlanReceiverTemplate), desc}, nil)

	code, ok := starlark.AsString(result)
	if !ok {
		t.Fatalf("expected string result, got %T", result)
	}

	// Valid Go syntax
	if _, err := format.Source([]byte(code)); err != nil {
		t.Fatalf("generated code is not valid Go:\n%s\nerror: %v", code, err)
	}

	// Struct definition with Receiver embedding
	if !strings.Contains(code, "type FilePlan struct") {
		t.Error("missing FilePlan struct definition")
	}
	if !strings.Contains(code, "Receiver\n") {
		t.Error("FilePlan should embed Receiver")
	}

	// Constructor initializes Receiver
	if !strings.Contains(code, `NewReceiver("plan.file")`) {
		t.Error("constructor should call NewReceiver")
	}

	// No inline starlark.Value methods (provided by Receiver)
	if strings.Contains(code, "func (p *FilePlan) String()") {
		t.Error("should not have inline String() — provided by Receiver")
	}
	if strings.Contains(code, "func (p *FilePlan) Hash()") {
		t.Error("should not have inline Hash() — provided by Receiver")
	}

	// Attr switch uses MakeAttr
	if !strings.Contains(code, `case "copy":`) {
		t.Error("missing case for copy in Attr switch")
	}
	if !strings.Contains(code, `case "remove":`) {
		t.Error("missing case for remove in Attr switch")
	}
	if !strings.Contains(code, `MakeAttr("plan.file.copy"`) {
		t.Error("Attr should use MakeAttr")
	}
	if strings.Contains(code, "starlark.NewBuiltin(") {
		t.Error("should not use starlark.NewBuiltin — use MakeAttr")
	}

	// NoSuchAttrError
	if !strings.Contains(code, `NoSuchAttrError("plan.file"`) {
		t.Error("should use NoSuchAttrError with namespace")
	}
	if strings.Contains(code, "starlark.NoSuchAttrError") {
		t.Error("should not use starlark.NoSuchAttrError")
	}

	// Method definitions
	if !strings.Contains(code, "func (p *FilePlan) copy(") {
		t.Error("missing copy method")
	}
	if !strings.Contains(code, "func (p *FilePlan) remove(") {
		t.Error("missing remove method")
	}

	// AttrNames sorted
	if !strings.Contains(code, `"copy", "remove"`) {
		t.Error("AttrNames should be sorted: copy, remove")
	}

	// Namespace
	if !strings.Contains(code, `"plan.file"`) {
		t.Error("missing namespace plan.file")
	}

	// Node ID includes category
	if !strings.Contains(code, `generateNodeID("file-copy")`) {
		t.Error("node ID should include category: file-copy")
	}
	if !strings.Contains(code, `generateNodeID("file-remove")`) {
		t.Error("node ID should include category: file-remove")
	}

	// Action uses MustGet with dotted name
	if !strings.Contains(code, `p.reg.MustGet("file.copy")`) {
		t.Error("Action should use p.reg.MustGet for file.copy")
	}
	if !strings.Contains(code, `p.reg.MustGet("file.remove")`) {
		t.Error("Action should use p.reg.MustGet for file.remove")
	}

	// Registry field
	if !strings.Contains(code, "reg") {
		t.Error("struct should have reg field")
	}

	// FillSlot calls
	if !strings.Contains(code, `FillSlot(node, p.graph, "source"`) {
		t.Error("missing FillSlot for source")
	}
	if !strings.Contains(code, `FillSlot(node, p.graph, "path"`) {
		t.Error("missing FillSlot for path")
	}
}

func TestGenerateGraphActions(t *testing.T) {
	r := NewGoReceiver()
	desc := buildTestDescriptor(t, fileMethodsFixture())
	// Graph actions use per-provider package
	must(t, desc.SetKey(starlark.String("package"), starlark.String("file")))

	result := callMethod(t, r, "generate",
		starlark.Tuple{starlark.String(testGraphActionsTemplate), desc}, nil)

	code, ok := starlark.AsString(result)
	if !ok {
		t.Fatalf("expected string result, got %T", result)
	}

	// Valid Go syntax
	if _, err := format.Source([]byte(code)); err != nil {
		t.Fatalf("generated code is not valid Go:\n%s\nerror: %v", code, err)
	}

	// Action structs use short name with Impl *Provider
	if !strings.Contains(code, "type Copy struct{ Impl *Provider }") {
		t.Error("missing Copy struct with Impl *Provider")
	}
	if !strings.Contains(code, "type Remove struct{ Impl *Provider }") {
		t.Error("missing Remove struct with Impl *Provider")
	}

	// Action names
	if !strings.Contains(code, `return "file.copy"`) {
		t.Error("missing file.copy action name")
	}
	if !strings.Contains(code, `return "file.remove"`) {
		t.Error("missing file.remove action name")
	}

	// Do method with slots signature
	if !strings.Contains(code, "Do(ctx *execution.Context, slots map[string]any) (execution.Result, execution.UndoState, error)") {
		t.Error("missing Do method signature")
	}

	// Undo method stub
	if !strings.Contains(code, "Undo(_ *execution.Context, _ map[string]any, _ execution.UndoState) error") {
		t.Error("missing Undo method stub")
	}

	// Register function
	if !strings.Contains(code, "func Register(reg *execution.ActionRegistry)") {
		t.Error("missing Register function")
	}

	// Slot readers with type assertions from slots map
	if !strings.Contains(code, `slots["source"].(string)`) {
		t.Error("missing typed slot reader for source")
	}
}

func TestGenerateRealtimeReceiver(t *testing.T) {
	r := NewGoReceiver()
	desc := buildTestDescriptor(t, fileMethodsFixture())

	result := callMethod(t, r, "generate",
		starlark.Tuple{starlark.String("realtime_receiver"), desc}, nil)

	code, ok := starlark.AsString(result)
	if !ok {
		t.Fatalf("expected string result, got %T", result)
	}

	// Valid Go syntax
	if _, err := format.Source([]byte(code)); err != nil {
		t.Fatalf("generated code is not valid Go:\n%s\nerror: %v", code, err)
	}

	// Struct definition
	if !strings.Contains(code, "type FileReceiver struct") {
		t.Error("missing FileReceiver struct")
	}

	// Constructor
	if !strings.Contains(code, `NewReceiver("file")`) {
		t.Error("missing NewReceiver call")
	}

	// Attr dispatch
	if !strings.Contains(code, `MakeAttr("file.copy"`) {
		t.Error("missing MakeAttr for file.copy")
	}
	if !strings.Contains(code, `MakeAttr("file.remove"`) {
		t.Error("missing MakeAttr for file.remove")
	}

	// NoSuchAttrError
	if !strings.Contains(code, `NoSuchAttrError("file"`) {
		t.Error("missing NoSuchAttrError")
	}
}

func TestGenerateGateRejectsUnmappedType(t *testing.T) {
	r := NewGoReceiver()
	desc := buildTestDescriptor(t, []map[string]any{
		{
			"name":    "Send",
			"returns": "(string, error)",
			"params": []map[string]any{
				{"name": "ch", "type": "chan string"},
			},
		},
	})

	thread := &starlark.Thread{Name: "test"}
	attr, _ := r.Attr("generate")
	fn := attr.(*starlark.Builtin)
	_, err := fn.CallInternal(thread, starlark.Tuple{starlark.String(testPlanReceiverTemplate), desc}, nil)
	if err == nil {
		t.Fatal("expected error for unmapped type")
	}
	if !strings.Contains(err.Error(), "chan string") {
		t.Errorf("error should mention unmapped type: %v", err)
	}
}

func TestGenerateGateRejectsBadReturn(t *testing.T) {
	r := NewGoReceiver()
	desc := buildTestDescriptor(t, []map[string]any{
		{
			"name":    "Check",
			"returns": "string",
			"params":  []map[string]any{},
		},
	})

	thread := &starlark.Thread{Name: "test"}
	attr, _ := r.Attr("generate")
	fn := attr.(*starlark.Builtin)
	_, err := fn.CallInternal(thread, starlark.Tuple{starlark.String(testPlanReceiverTemplate), desc}, nil)
	if err == nil {
		t.Fatal("expected error for bad return signature")
	}
	if !strings.Contains(err.Error(), "must return error or (T, error)") {
		t.Errorf("error should mention return format: %v", err)
	}
}

func TestGenerateVariadicParam(t *testing.T) {
	r := NewGoReceiver()
	desc := buildTestDescriptor(t, []map[string]any{
		{
			"name":    "Install",
			"returns": "(string, error)",
			"params": []map[string]any{
				{"name": "packages", "type": "string", "variadic": true},
			},
		},
	})

	result := callMethod(t, r, "generate",
		starlark.Tuple{starlark.String(testPlanReceiverTemplate), desc}, nil)

	code, ok := starlark.AsString(result)
	if !ok {
		t.Fatalf("expected string result, got %T", result)
	}

	// Valid Go syntax
	if _, err := format.Source([]byte(code)); err != nil {
		t.Fatalf("generated code is not valid Go:\n%s\nerror: %v", code, err)
	}

	// Should have the install method
	if !strings.Contains(code, "func (p *FilePlan) install(") {
		t.Error("missing install method")
	}

	// Should unpack the packages param
	if !strings.Contains(code, `"packages"`) {
		t.Error("missing packages param in unpack")
	}
}

func TestGoGenerateAttr(t *testing.T) {
	r := NewGoReceiver()

	// Check AttrNames includes "generate"
	names := r.AttrNames()
	found := false
	for _, n := range names {
		if n == "generate" {
			found = true
			break
		}
	}
	if !found {
		t.Error("AttrNames() should include 'generate'")
	}

	// Check Attr("generate") returns a builtin
	attr, err := r.Attr("generate")
	if err != nil {
		t.Fatalf("Attr(generate): %v", err)
	}
	if _, ok := attr.(*starlark.Builtin); !ok {
		t.Fatalf("Attr(generate) returned %T, want *starlark.Builtin", attr)
	}
}

func TestGoTemplateAttr(t *testing.T) {
	r := NewGoReceiver()

	// Check AttrNames includes "template"
	names := r.AttrNames()
	found := false
	for _, n := range names {
		if n == "template" {
			found = true
			break
		}
	}
	if !found {
		t.Error("AttrNames() should include 'template'")
	}

	// Check Attr("template") returns a builtin
	attr, err := r.Attr("template")
	if err != nil {
		t.Fatalf("Attr(template): %v", err)
	}
	if _, ok := attr.(*starlark.Builtin); !ok {
		t.Fatalf("Attr(template) returned %T, want *starlark.Builtin", attr)
	}
}

func TestGoTemplateReturnsContent(t *testing.T) {
	r := NewGoReceiver()

	result := callMethod(t, r, "template",
		starlark.Tuple{starlark.String("realtime_receiver")}, nil)

	content, ok := starlark.AsString(result)
	if !ok {
		t.Fatalf("expected string result, got %T", result)
	}

	if !strings.Contains(content, "{{.StructName}}Receiver") {
		t.Error("template content should contain StructName placeholder")
	}
	if !strings.Contains(content, "Code generated by go.generate") {
		t.Error("template content should contain generated header")
	}
}

func TestGoTemplateUnknownName(t *testing.T) {
	r := NewGoReceiver()
	thread := &starlark.Thread{Name: "test"}
	attr, _ := r.Attr("template")
	fn := attr.(*starlark.Builtin)
	_, err := fn.CallInternal(thread, starlark.Tuple{starlark.String("nonexistent")}, nil)
	if err == nil {
		t.Fatal("expected error for unknown template name")
	}
	if !strings.Contains(err.Error(), "unknown builtin") {
		t.Errorf("error should mention unknown builtin: %v", err)
	}
}

func TestGenerateGraphActionsDelegation(t *testing.T) {
	r := NewGoReceiver()
	desc := buildTestDescriptor(t, []map[string]any{
		{
			"name":    "Link",
			"returns": "(string, error)",
			"params": []map[string]any{
				{"name": "source", "type": "string"},
				{"name": "path", "type": "string"},
			},
		},
		{
			"name":    "Copy",
			"returns": "(string, error)",
			"params": []map[string]any{
				{"name": "path", "type": "string"},
			},
		},
		{
			"name":    "Render",
			"returns": "(string, error)",
			"params": []map[string]any{
				{"name": "source", "type": "string"},
			},
		},
	})
	must(t, desc.SetKey(starlark.String("package"), starlark.String("file")))
	must(t, desc.SetKey(starlark.String("namespace"), starlark.String("file")))
	must(t, desc.SetKey(starlark.String("impl_type"), starlark.String("Provider")))

	result := callMethod(t, r, "generate",
		starlark.Tuple{starlark.String(testGraphActionsTemplate), desc}, nil)

	code, ok := starlark.AsString(result)
	if !ok {
		t.Fatalf("expected string result, got %T", result)
	}

	// Valid Go syntax
	if _, err := format.Source([]byte(code)); err != nil {
		t.Fatalf("generated code is not valid Go:\n%s\nerror: %v", code, err)
	}

	// Action structs always have Impl *Provider
	if !strings.Contains(code, "type Link struct{ Impl *Provider }") {
		t.Error("Link should have Impl *Provider field")
	}
	if !strings.Contains(code, "type Copy struct{ Impl *Provider }") {
		t.Error("Copy should have Impl *Provider field")
	}
	if !strings.Contains(code, "type Render struct{ Impl *Provider }") {
		t.Error("Render should have Impl *Provider field")
	}

	// No generated interface — use concrete struct directly
	if strings.Contains(code, "interface") {
		t.Error("should not generate an interface")
	}

	// All actions delegate via Impl (exported)
	if !strings.Contains(code, "o.Impl.Link(source, path)") {
		t.Error("Link action should delegate to Impl.Link")
	}
	if !strings.Contains(code, "o.Impl.Copy(path)") {
		t.Error("Copy action should delegate to Impl.Copy")
	}
	if !strings.Contains(code, "o.Impl.Render(source)") {
		t.Error("Render action should delegate to Impl.Render")
	}

	// Slot readers use slots map
	if !strings.Contains(code, `slots["source"].(string)`) {
		t.Error("slot readers should use slots map")
	}

	// Undo stubs
	if !strings.Contains(code, "func (o *Link) Undo(") {
		t.Error("missing Undo for Link")
	}
	if !strings.Contains(code, "func (o *Copy) Undo(") {
		t.Error("missing Undo for Copy")
	}

	// Register function with Provider
	if !strings.Contains(code, "func Register(reg *execution.ActionRegistry)") {
		t.Error("missing Register function")
	}
	if !strings.Contains(code, "&Link{Impl: p}") {
		t.Error("Register should pass Impl to actions")
	}
}

func TestGoMappingRoundTrip(t *testing.T) {
	r := NewGoReceiver()
	desc := buildTestDescriptor(t, []map[string]any{
		{
			"name":    "Link",
			"returns": "(string, error)",
			"params": []map[string]any{
				{"name": "source", "type": "string"},
				{"name": "path", "type": "string"},
			},
		},
		{
			"name":    "Copy",
			"returns": "(string, error)",
			"params": []map[string]any{
				{"name": "path", "type": "string"},
			},
		},
		{
			"name":    "Render",
			"returns": "(string, error)",
			"params": []map[string]any{
				{"name": "source", "type": "string"},
			},
		},
	})
	must(t, desc.SetKey(starlark.String("package"), starlark.String("execution")))
	must(t, desc.SetKey(starlark.String("namespace"), starlark.String("file")))
	must(t, desc.SetKey(starlark.String("impl_type"), starlark.String("fileOps")))

	result := callMethod(t, r, "mapping", starlark.Tuple{desc}, nil)

	yamlStr, ok := starlark.AsString(result)
	if !ok {
		t.Fatalf("expected string result, got %T", result)
	}

	// Parse the YAML output
	var mapping mappingFile
	if err := yaml.Unmarshal([]byte(yamlStr), &mapping); err != nil {
		t.Fatalf("failed to parse mapping YAML: %v\n%s", err, yamlStr)
	}

	// Verify top-level fields
	if mapping.Version != "1.0" {
		t.Errorf("expected version 1.0, got %q", mapping.Version)
	}
	if mapping.Struct != "fileOps" {
		t.Errorf("expected struct fileOps, got %q", mapping.Struct)
	}
	if mapping.Package != "execution" {
		t.Errorf("expected package execution, got %q", mapping.Package)
	}
	if mapping.Category != "file" {
		t.Errorf("expected category file, got %q", mapping.Category)
	}

	// Verify operations
	if len(mapping.Operations) != 3 {
		t.Fatalf("expected 3 operations, got %d", len(mapping.Operations))
	}

	// Link
	link := mapping.Operations[0]
	if link.Name != "file.link" {
		t.Errorf("expected file.link, got %q", link.Name)
	}
	if link.GoMethod != "Link" {
		t.Errorf("expected GoMethod Link, got %q", link.GoMethod)
	}
	if len(link.Params) != 2 {
		t.Fatalf("expected 2 params, got %d", len(link.Params))
	}
	if link.Params[0].Name != "source" || link.Params[0].Type != "string" {
		t.Errorf("unexpected first param: %+v", link.Params[0])
	}

	// Copy
	copyOp := mapping.Operations[1]
	if copyOp.Name != "file.copy" {
		t.Errorf("expected file.copy, got %q", copyOp.Name)
	}
	if len(copyOp.Params) != 1 {
		t.Fatalf("expected 1 param, got %d", len(copyOp.Params))
	}

	// Render
	render := mapping.Operations[2]
	if render.Name != "file.render" {
		t.Errorf("expected file.render, got %q", render.Name)
	}

	// Verify header comment
	if !strings.Contains(yamlStr, "# Generated by go.mapping") {
		t.Error("missing header comment")
	}
}

func TestGoMappingAttr(t *testing.T) {
	r := NewGoReceiver()

	// Check AttrNames includes "mapping"
	names := r.AttrNames()
	found := false
	for _, n := range names {
		if n == "mapping" {
			found = true
			break
		}
	}
	if !found {
		t.Error("AttrNames() should include 'mapping'")
	}

	// Check Attr("mapping") returns a builtin
	attr, err := r.Attr("mapping")
	if err != nil {
		t.Fatalf("Attr(mapping): %v", err)
	}
	if _, ok := attr.(*starlark.Builtin); !ok {
		t.Fatalf("Attr(mapping) returned %T, want *starlark.Builtin", attr)
	}
}

func TestGoMappingFrameworkTypes(t *testing.T) {
	r := NewGoReceiver()
	desc := buildTestDescriptor(t, []map[string]any{
		{
			"name":    "Decrypt",
			"returns": "([]byte, error)",
			"params": []map[string]any{
				{"name": "decryptor", "type": "func(string, []byte) ([]byte, error)"},
				{"name": "source", "type": "string"},
				{"name": "content", "type": "[]byte"},
			},
		},
		{
			"name":    "Shell",
			"returns": "error",
			"params": []map[string]any{
				{"name": "command", "type": "string"},
				{"name": "output", "type": "io.Writer"},
			},
		},
		{
			"name":    "Copy",
			"returns": "(string, error)",
			"params": []map[string]any{
				{"name": "path", "type": "string"},
				{"name": "mode", "type": "os.FileMode"},
				{"name": "content", "type": "[]byte"},
			},
		},
	})
	must(t, desc.SetKey(starlark.String("package"), starlark.String("execution")))
	must(t, desc.SetKey(starlark.String("impl_type"), starlark.String("EncryptionService")))

	result := callMethod(t, r, "mapping", starlark.Tuple{desc}, nil)

	yamlStr, ok := starlark.AsString(result)
	if !ok {
		t.Fatalf("expected string result, got %T", result)
	}

	// Parse the YAML output
	var mapping mappingFile
	if err := yaml.Unmarshal([]byte(yamlStr), &mapping); err != nil {
		t.Fatalf("failed to parse mapping YAML: %v\n%s", err, yamlStr)
	}

	if len(mapping.Operations) != 3 {
		t.Fatalf("expected 3 operations, got %d", len(mapping.Operations))
	}

	// Decrypt has framework params recorded
	decrypt := mapping.Operations[0]
	if decrypt.Name != "file.decrypt" {
		t.Errorf("expected file.decrypt, got %q", decrypt.Name)
	}
	if len(decrypt.Params) != 3 {
		t.Fatalf("expected 3 params, got %d", len(decrypt.Params))
	}
	if decrypt.Params[0].Type != "func(string, []byte) ([]byte, error)" {
		t.Errorf("expected func type, got %q", decrypt.Params[0].Type)
	}

	// Shell has error-only return and io.Writer param
	shell := mapping.Operations[1]
	if shell.Name != "file.shell" {
		t.Errorf("expected file.shell, got %q", shell.Name)
	}
	if len(shell.Params) != 2 {
		t.Fatalf("expected 2 params, got %d", len(shell.Params))
	}
}

func TestGoMappingGateEnforcement(t *testing.T) {
	t.Run("unmapped type", func(t *testing.T) {
		r := NewGoReceiver()
		desc := buildTestDescriptor(t, []map[string]any{
			{
				"name":    "Send",
				"returns": "(string, error)",
				"params": []map[string]any{
					{"name": "ch", "type": "chan string"},
				},
			},
		})

		thread := &starlark.Thread{Name: "test"}
		attr, _ := r.Attr("mapping")
		fn := attr.(*starlark.Builtin)
		_, err := fn.CallInternal(thread, starlark.Tuple{desc}, nil)
		if err == nil {
			t.Fatal("expected error for unmapped type")
		}
		if !strings.Contains(err.Error(), "chan string") {
			t.Errorf("error should mention unmapped type: %v", err)
		}
	})

	t.Run("bad return", func(t *testing.T) {
		r := NewGoReceiver()
		desc := buildTestDescriptor(t, []map[string]any{
			{
				"name":    "Check",
				"returns": "string",
				"params":  []map[string]any{},
			},
		})

		thread := &starlark.Thread{Name: "test"}
		attr, _ := r.Attr("mapping")
		fn := attr.(*starlark.Builtin)
		_, err := fn.CallInternal(thread, starlark.Tuple{desc}, nil)
		if err == nil {
			t.Fatal("expected error for bad return signature")
		}
		if !strings.Contains(err.Error(), "must return error or (T, error)") {
			t.Errorf("error should mention return format: %v", err)
		}
	})
}

func TestInferContentModel(t *testing.T) {
	tests := []struct {
		name      string
		valueType string
		params    []paramInfo
		want      string
	}{
		{
			name:      "error-only return",
			valueType: "",
			params:    []paramInfo{{GoType: "[]byte"}},
			want:      "none",
		},
		{
			name:      "string return with []byte last param",
			valueType: "string",
			params: []paramInfo{
				{GoType: "string"},
				{GoType: "[]byte"},
			},
			want: "consumer",
		},
		{
			name:      "[]byte return with []byte last param",
			valueType: "[]byte",
			params: []paramInfo{
				{GoType: "string"},
				{GoType: "[]byte"},
			},
			want: "transformer",
		},
		{
			name:      "string return without []byte last param",
			valueType: "string",
			params: []paramInfo{
				{GoType: "string"},
			},
			want: "none",
		},
		{
			name:      "no params",
			valueType: "string",
			params:    nil,
			want:      "none",
		},
		{
			name:      "bool return with []byte last param",
			valueType: "bool",
			params: []paramInfo{
				{GoType: "[]byte"},
			},
			want: "none",
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := inferContentModel(tc.valueType, tc.params)
			if got != tc.want {
				t.Errorf("inferContentModel(%q, ...) = %q, want %q", tc.valueType, got, tc.want)
			}
		})
	}
}

func TestIsContentParam(t *testing.T) {
	consumer := methodInfo{
		GoName:       "Decrypt",
		ContentModel: "consumer",
		Params: []paramInfo{
			{GoName: "source", GoType: "string"},
			{GoName: "content", GoType: "[]byte"},
		},
	}
	// Last []byte is content
	if !isContentParam(consumer.Params[1], consumer) {
		t.Error("last []byte should be content param in consumer")
	}
	// String is not content
	if isContentParam(consumer.Params[0], consumer) {
		t.Error("string param should not be content param")
	}

	none := methodInfo{
		GoName:       "Copy",
		ContentModel: "none",
		Params: []paramInfo{
			{GoName: "path", GoType: "string"},
		},
	}
	if isContentParam(none.Params[0], none) {
		t.Error("no params should be content in none model")
	}
}

func TestGenerateGraphActionsConsumer(t *testing.T) {
	r := NewGoReceiver()
	desc := buildTestDescriptor(t, []map[string]any{
		{
			"name":    "Decrypt",
			"returns": "(string, error)",
			"params": []map[string]any{
				{"name": "source", "type": "string"},
				{"name": "content", "type": "[]byte"},
			},
		},
	})
	must(t, desc.SetKey(starlark.String("package"), starlark.String("encryption")))
	must(t, desc.SetKey(starlark.String("impl_type"), starlark.String("Provider")))

	result := callMethod(t, r, "generate",
		starlark.Tuple{starlark.String(testGraphActionsTemplate), desc}, nil)

	code, ok := starlark.AsString(result)
	if !ok {
		t.Fatalf("expected string result, got %T", result)
	}

	if _, err := format.Source([]byte(code)); err != nil {
		t.Fatalf("generated code is not valid Go:\n%s\nerror: %v", code, err)
	}

	// Content read via slot with optional assertion
	if !strings.Contains(code, `content, _ := slots["content"].([]byte)`) {
		t.Error("consumer should read content via slots map with optional assertion")
	}

	// Dry-run checksum
	if !strings.Contains(code, "ctx.TargetChecksum = ChecksumBytes(content)") {
		t.Error("consumer dry-run should set TargetChecksum")
	}

	// Delegation uses Impl (exported)
	if !strings.Contains(code, "o.Impl.Decrypt(source, content)") {
		t.Error("consumer should delegate to Impl.Decrypt")
	}

	// Dry-run format only includes starlark-facing params (source, not content)
	if !strings.Contains(code, `[dry-run] file.decrypt %v`) {
		t.Error("dry-run should format starlark-facing params only")
	}
}

func TestGenerateGraphActionsTransformer(t *testing.T) {
	r := NewGoReceiver()
	desc := buildTestDescriptor(t, []map[string]any{
		{
			"name":    "Transform",
			"returns": "([]byte, error)",
			"params": []map[string]any{
				{"name": "source", "type": "string"},
				{"name": "content", "type": "[]byte"},
			},
		},
	})
	must(t, desc.SetKey(starlark.String("package"), starlark.String("template")))
	must(t, desc.SetKey(starlark.String("impl_type"), starlark.String("Provider")))

	result := callMethod(t, r, "generate",
		starlark.Tuple{starlark.String(testGraphActionsTemplate), desc}, nil)

	code, ok := starlark.AsString(result)
	if !ok {
		t.Fatalf("expected string result, got %T", result)
	}

	if _, err := format.Source([]byte(code)); err != nil {
		t.Fatalf("generated code is not valid Go:\n%s\nerror: %v", code, err)
	}

	// Content read via slot with optional assertion
	if !strings.Contains(code, `content, _ := slots["content"].([]byte)`) {
		t.Error("transformer should read content via slots map with optional assertion")
	}

	// Transformer returns result directly (no StoreContent)
	if !strings.Contains(code, "return result, nil, nil") {
		t.Error("transformer should return result as first value")
	}
	if strings.Contains(code, "StoreContent") {
		t.Error("transformer should not use StoreContent")
	}

	// No checksum in transformer dry-run
	if strings.Contains(code, "TargetChecksum") {
		t.Error("transformer should not set TargetChecksum")
	}
}

func TestGenerateGraphActionsFramework(t *testing.T) {
	r := NewGoReceiver()
	desc := buildTestDescriptor(t, []map[string]any{
		{
			"name":    "Shell",
			"returns": "error",
			"params": []map[string]any{
				{"name": "command", "type": "string"},
				{"name": "output", "type": "io.Writer"},
			},
		},
		{
			"name":    "Move",
			"returns": "error",
			"params": []map[string]any{
				{"name": "source", "type": "string"},
				{"name": "path", "type": "string"},
				{"name": "gitMv", "type": "func(string, string) error"},
			},
		},
	})
	must(t, desc.SetKey(starlark.String("package"), starlark.String("shell")))
	must(t, desc.SetKey(starlark.String("impl_type"), starlark.String("Provider")))

	result := callMethod(t, r, "generate",
		starlark.Tuple{starlark.String(testGraphActionsTemplate), desc}, nil)

	code, ok := starlark.AsString(result)
	if !ok {
		t.Fatalf("expected string result, got %T", result)
	}

	if _, err := format.Source([]byte(code)); err != nil {
		t.Fatalf("generated code is not valid Go:\n%s\nerror: %v", code, err)
	}

	// io.Writer read from ctx.Logger
	if !strings.Contains(code, "output := ctx.Logger") {
		t.Error("io.Writer should be read from ctx.Logger")
	}

	// func type read from slots map
	if !strings.Contains(code, `slots["git_mv"].(func(string, string) error)`) {
		t.Error("func param should be read via slots map assertion")
	}

	// Dry-run skips non-starlark-facing params
	if strings.Contains(code, "output") && strings.Contains(code, `[dry-run] file.shell %v %v`) {
		t.Error("dry-run should not include io.Writer in format")
	}
}

func TestGenerateGraphActionsErrorOnly(t *testing.T) {
	r := NewGoReceiver()
	desc := buildTestDescriptor(t, []map[string]any{
		{
			"name":    "Remove",
			"returns": "error",
			"params": []map[string]any{
				{"name": "path", "type": "string"},
			},
		},
	})
	must(t, desc.SetKey(starlark.String("package"), starlark.String("file")))
	must(t, desc.SetKey(starlark.String("impl_type"), starlark.String("Provider")))

	result := callMethod(t, r, "generate",
		starlark.Tuple{starlark.String(testGraphActionsTemplate), desc}, nil)

	code, ok := starlark.AsString(result)
	if !ok {
		t.Fatalf("expected string result, got %T", result)
	}

	if _, err := format.Source([]byte(code)); err != nil {
		t.Fatalf("generated code is not valid Go:\n%s\nerror: %v", code, err)
	}

	// Error-only return: three values with delegation
	if !strings.Contains(code, "return nil, nil, o.Impl.Remove(path)") {
		t.Error("error-only should return nil, nil, delegation")
	}

	// No content handling
	if strings.Contains(code, "ContentFor") {
		t.Error("error-only should not use ContentFor")
	}
	if strings.Contains(code, "TargetChecksum") {
		t.Error("error-only should not set TargetChecksum")
	}
}

func TestPlanReceiverSkipsFramework(t *testing.T) {
	r := NewGoReceiver()
	desc := buildTestDescriptor(t, []map[string]any{
		{
			"name":    "Decrypt",
			"returns": "(string, error)",
			"params": []map[string]any{
				{"name": "decryptor", "type": "func(string, []byte) ([]byte, error)"},
				{"name": "source", "type": "string"},
				{"name": "content", "type": "[]byte"},
			},
		},
		{
			"name":    "Shell",
			"returns": "error",
			"params": []map[string]any{
				{"name": "command", "type": "string"},
				{"name": "output", "type": "io.Writer"},
			},
		},
	})

	result := callMethod(t, r, "generate",
		starlark.Tuple{starlark.String(testPlanReceiverTemplate), desc}, nil)

	code, ok := starlark.AsString(result)
	if !ok {
		t.Fatalf("expected string result, got %T", result)
	}

	if _, err := format.Source([]byte(code)); err != nil {
		t.Fatalf("generated code is not valid Go:\n%s\nerror: %v", code, err)
	}

	// Starlark-facing params present in FillSlot
	if !strings.Contains(code, `FillSlot(node, p.graph, "source"`) {
		t.Error("source should have FillSlot")
	}
	if !strings.Contains(code, `FillSlot(node, p.graph, "command"`) {
		t.Error("command should have FillSlot")
	}

	// Non-starlark-facing params absent from FillSlot
	if strings.Contains(code, `FillSlot(node, p.graph, "decryptor"`) {
		t.Error("func type should NOT have FillSlot")
	}
	if strings.Contains(code, `FillSlot(node, p.graph, "output"`) {
		t.Error("io.Writer should NOT have FillSlot")
	}
	if strings.Contains(code, `FillSlot(node, p.graph, "content"`) {
		t.Error("content []byte should NOT have FillSlot")
	}

	// Non-starlark-facing params absent from UnpackArgs
	if strings.Contains(code, `"decryptor"`) {
		t.Error("func type should NOT appear in UnpackArgs")
	}
	if strings.Contains(code, `"output"`) {
		t.Error("io.Writer should NOT appear in UnpackArgs")
	}
	if strings.Contains(code, `"content"`) {
		t.Error("content []byte should NOT appear in UnpackArgs")
	}
}

func TestValidateCompensableReturn(t *testing.T) {
	tests := []struct {
		input     string
		wantValue string
		wantErr   bool
	}{
		// State-only: (map[string]any, error)
		{"(map[string]any, error)", "", false},
		// Value + state: (T, map[string]any, error)
		{"(string, map[string]any, error)", "string", false},
		{"([]byte, map[string]any, error)", "[]byte", false},
		{"(bool, map[string]any, error)", "bool", false},
		// Invalid
		{"error", "", true},
		{"(string, error)", "", true},
		{"", "", true},
		{"string", "", true},
		{"(map[string]any)", "", true},
		{"(, map[string]any, error)", "", true},
	}
	for _, tc := range tests {
		t.Run(tc.input, func(t *testing.T) {
			got, err := validateCompensableReturn(tc.input)
			if tc.wantErr {
				if err == nil {
					t.Errorf("expected error for %q, got value %q", tc.input, got)
				}
			} else {
				if err != nil {
					t.Errorf("unexpected error for %q: %v", tc.input, err)
				}
				if got != tc.wantValue {
					t.Errorf("validateCompensableReturn(%q) = %q, want %q", tc.input, got, tc.wantValue)
				}
			}
		})
	}
}

func TestGenerateGraphActionsCompensable(t *testing.T) {
	r := NewGoReceiver()
	desc := buildTestDescriptor(t, []map[string]any{
		{
			"name":        "Install",
			"returns":     "(map[string]any, error)",
			"compensable": true,
			"params": []map[string]any{
				{"name": "name", "type": "string"},
				{"name": "version", "type": "string"},
			},
		},
	})
	must(t, desc.SetKey(starlark.String("package"), starlark.String("pkg")))
	must(t, desc.SetKey(starlark.String("impl_type"), starlark.String("Provider")))

	result := callMethod(t, r, "generate",
		starlark.Tuple{starlark.String(testGraphActionsTemplate), desc}, nil)

	code, ok := starlark.AsString(result)
	if !ok {
		t.Fatalf("expected string result, got %T", result)
	}

	if _, err := format.Source([]byte(code)); err != nil {
		t.Fatalf("generated code is not valid Go:\n%s\nerror: %v", code, err)
	}

	// Do captures state from forward method
	if !strings.Contains(code, "state, err := o.Impl.Install(name, version)") {
		t.Error("compensable Do should capture state from forward method")
	}
	if !strings.Contains(code, "return nil, state, err") {
		t.Error("compensable Do should return state as UndoState")
	}

	// Undo delegates to CompensateInstall
	if !strings.Contains(code, "func (o *Install) Undo(_ *execution.Context, _ map[string]any, state execution.UndoState) error") {
		t.Error("compensable Undo should accept state parameter")
	}
	if !strings.Contains(code, "s, _ := state.(map[string]any)") {
		t.Error("compensable Undo should type-assert state")
	}
	if !strings.Contains(code, "return o.Impl.CompensateInstall(s)") {
		t.Error("compensable Undo should delegate to Impl.CompensateInstall")
	}

	// Non-compensable Undo uses blank identifiers
	if strings.Contains(code, "_ execution.UndoState") {
		t.Error("compensable Undo should NOT blank the state parameter")
	}
}

func TestGenerateGraphActionsCompensableWithValue(t *testing.T) {
	r := NewGoReceiver()
	desc := buildTestDescriptor(t, []map[string]any{
		{
			"name":        "Copy",
			"returns":     "(string, map[string]any, error)",
			"compensable": true,
			"params": []map[string]any{
				{"name": "source", "type": "string"},
				{"name": "path", "type": "string"},
				{"name": "content", "type": "[]byte"},
			},
		},
	})
	must(t, desc.SetKey(starlark.String("package"), starlark.String("file")))
	must(t, desc.SetKey(starlark.String("impl_type"), starlark.String("Provider")))

	result := callMethod(t, r, "generate",
		starlark.Tuple{starlark.String(testGraphActionsTemplate), desc}, nil)

	code, ok := starlark.AsString(result)
	if !ok {
		t.Fatalf("expected string result, got %T", result)
	}

	if _, err := format.Source([]byte(code)); err != nil {
		t.Fatalf("generated code is not valid Go:\n%s\nerror: %v", code, err)
	}

	// Consumer model with compensation: captures checksum + state
	if !strings.Contains(code, "checksum, state, err := o.Impl.Copy(source, path, content)") {
		t.Error("compensable consumer should capture checksum and state")
	}
	if !strings.Contains(code, "ctx.TargetChecksum = checksum") {
		t.Error("compensable consumer should set TargetChecksum")
	}
	if !strings.Contains(code, "return nil, state, nil") {
		t.Error("compensable consumer should return state as UndoState")
	}

	// Undo delegates to CompensateCopy
	if !strings.Contains(code, "return o.Impl.CompensateCopy(s)") {
		t.Error("compensable Undo should delegate to Impl.CompensateCopy")
	}
}

func TestGenerateGraphActionsNonCompensableUndo(t *testing.T) {
	r := NewGoReceiver()
	desc := buildTestDescriptor(t, []map[string]any{
		{
			"name":    "Remove",
			"returns": "error",
			"params": []map[string]any{
				{"name": "path", "type": "string"},
			},
		},
	})
	must(t, desc.SetKey(starlark.String("package"), starlark.String("file")))
	must(t, desc.SetKey(starlark.String("impl_type"), starlark.String("Provider")))

	result := callMethod(t, r, "generate",
		starlark.Tuple{starlark.String(testGraphActionsTemplate), desc}, nil)

	code, ok := starlark.AsString(result)
	if !ok {
		t.Fatalf("expected string result, got %T", result)
	}

	if _, err := format.Source([]byte(code)); err != nil {
		t.Fatalf("generated code is not valid Go:\n%s\nerror: %v", code, err)
	}

	// Non-compensable Undo uses blank identifiers and returns nil
	if !strings.Contains(code, "func (o *Remove) Undo(_ *execution.Context, _ map[string]any, _ execution.UndoState) error") {
		t.Error("non-compensable Undo should blank all params")
	}
	if !strings.Contains(code, "return nil") {
		t.Error("non-compensable Undo should return nil")
	}
	if strings.Contains(code, "CompensateRemove") {
		t.Error("non-compensable Undo should NOT delegate to a Compensate method")
	}
}

func TestRealtimeProviderBodyErrorOnly(t *testing.T) {
	m := methodInfo{
		GoName:     "Remove",
		SnakeName:  "remove",
		ReturnType: "", // gate-processed: error → ""
		Params: []paramInfo{
			{GoName: "path", SnakeName: "path", GoType: "string"},
		},
	}
	body := tplRealtimeProviderBody(m)
	if !strings.Contains(body, "r.provider.Remove(path)") {
		t.Errorf("should delegate to r.provider.Remove, got:\n%s", body)
	}
	if !strings.Contains(body, "return starlark.None, nil") {
		t.Errorf("error-only should return starlark.None, got:\n%s", body)
	}
}

func TestRealtimeProviderBodyStringReturn(t *testing.T) {
	m := methodInfo{
		GoName:     "Source",
		SnakeName:  "source",
		ReturnType: "string", // gate-processed: (string, error) → "string"
		Params: []paramInfo{
			{GoName: "path", SnakeName: "path", GoType: "string"},
		},
	}
	body := tplRealtimeProviderBody(m)
	if !strings.Contains(body, "r.provider.Source(path)") {
		t.Errorf("should delegate to r.provider.Source, got:\n%s", body)
	}
	if !strings.Contains(body, "starlark.String(result)") {
		t.Errorf("should convert string result, got:\n%s", body)
	}
}

func TestRealtimeProviderBodyBytesReturn(t *testing.T) {
	m := methodInfo{
		GoName:     "Download",
		SnakeName:  "download",
		ReturnType: "[]byte", // gate-processed: ([]byte, error) → "[]byte"
		Params: []paramInfo{
			{GoName: "url", SnakeName: "url", GoType: "string"},
		},
	}
	body := tplRealtimeProviderBody(m)
	if !strings.Contains(body, "r.provider.Download(url)") {
		t.Errorf("should delegate to r.provider.Download, got:\n%s", body)
	}
	if !strings.Contains(body, "starlark.Bytes(result)") {
		t.Errorf("should convert []byte result, got:\n%s", body)
	}
}

func TestRealtimeProviderBodyCompensableStateOnly(t *testing.T) {
	m := methodInfo{
		GoName:      "Install",
		SnakeName:   "install",
		ReturnType:  "", // gate-processed: (map[string]any, error) → ""
		Compensable: true,
		Params: []paramInfo{
			{GoName: "name", SnakeName: "name", GoType: "string"},
		},
	}
	body := tplRealtimeProviderBody(m)
	if !strings.Contains(body, "_, err := r.provider.Install(name)") {
		t.Errorf("compensable state-only should discard state, got:\n%s", body)
	}
	if !strings.Contains(body, "return starlark.None, nil") {
		t.Errorf("compensable state-only should return None, got:\n%s", body)
	}
}

func TestRealtimeProviderBodyCompensableWithValue(t *testing.T) {
	m := methodInfo{
		GoName:      "Copy",
		SnakeName:   "copy",
		ReturnType:  "string", // gate-processed: (string, map[string]any, error) → "string"
		Compensable: true,
		Params: []paramInfo{
			{GoName: "path", SnakeName: "path", GoType: "string"},
		},
	}
	body := tplRealtimeProviderBody(m)
	if !strings.Contains(body, "result, _, err := r.provider.Copy(path)") {
		t.Errorf("compensable with value should capture result and discard state, got:\n%s", body)
	}
	if !strings.Contains(body, "starlark.String(result)") {
		t.Errorf("should convert string result, got:\n%s", body)
	}
}

func TestRealtimeProviderBodyIOWriter(t *testing.T) {
	m := methodInfo{
		GoName:     "Shell",
		SnakeName:  "shell",
		ReturnType: "", // gate-processed: error → ""
		Params: []paramInfo{
			{GoName: "command", SnakeName: "command", GoType: "string"},
			{GoName: "output", SnakeName: "output", GoType: "io.Writer"},
		},
	}
	body := tplRealtimeProviderBody(m)
	if !strings.Contains(body, "r.provider.Shell(command, r.output)") {
		t.Errorf("io.Writer should map to r.output, got:\n%s", body)
	}
}

func TestRealtimeProviderBodyFileMode(t *testing.T) {
	m := methodInfo{
		GoName:     "Mkdir",
		SnakeName:  "mkdir",
		ReturnType: "", // gate-processed: error → ""
		Params: []paramInfo{
			{GoName: "path", SnakeName: "path", GoType: "string"},
			{GoName: "mode", SnakeName: "mode", GoType: "os.FileMode"},
		},
	}
	body := tplRealtimeProviderBody(m)
	if !strings.Contains(body, "r.provider.Mkdir(path, os.FileMode(mode))") {
		t.Errorf("os.FileMode should be cast from int, got:\n%s", body)
	}
}

func TestRealtimeProviderBodyStringSlice(t *testing.T) {
	m := methodInfo{
		GoName:      "Install",
		SnakeName:   "install",
		ReturnType:  "", // gate-processed: (map[string]any, error) → ""
		Compensable: true,
		Params: []paramInfo{
			{GoName: "packages", SnakeName: "packages", GoType: "[]string"},
			{GoName: "manager", SnakeName: "manager", GoType: "string"},
			{GoName: "cask", SnakeName: "cask", GoType: "bool"},
		},
	}
	body := tplRealtimeProviderBody(m)
	if !strings.Contains(body, "listToStringSlice(packages)") {
		t.Errorf("[]string should use listToStringSlice, got:\n%s", body)
	}
	if !strings.Contains(body, "r.provider.Install(listToStringSlice(packages), manager, cask)") {
		t.Errorf("should pass all args in order, got:\n%s", body)
	}
}

func TestRealtimeProviderBodyCallback(t *testing.T) {
	m := methodInfo{
		GoName:     "Move",
		SnakeName:  "move",
		ReturnType: "", // gate-processed: error → ""
		Params: []paramInfo{
			{GoName: "gitMv", SnakeName: "git_mv", GoType: "func(string, string) error"},
			{GoName: "source", SnakeName: "source", GoType: "string"},
			{GoName: "path", SnakeName: "path", GoType: "string"},
		},
	}
	body := tplRealtimeProviderBody(m)
	if !strings.Contains(body, "r.provider.Move(nil, source, path)") {
		t.Errorf("engine-injected callback should pass nil, got:\n%s", body)
	}
}

func TestRealtimeProviderBodyDictConversion(t *testing.T) {
	m := methodInfo{
		GoName:     "Render",
		SnakeName:  "render",
		ReturnType: "[]byte", // gate-processed: ([]byte, error) → "[]byte"
		Params: []paramInfo{
			{GoName: "templateData", SnakeName: "template_data", GoType: "map[string]any"},
			{GoName: "source", SnakeName: "source", GoType: "string"},
		},
	}
	body := tplRealtimeProviderBody(m)
	// Must pre-compute dict conversion (multi-return)
	if !strings.Contains(body, "templateDataMap, err := starlarkDictToMap(templateData)") {
		t.Errorf("should pre-compute dict conversion, got:\n%s", body)
	}
	if !strings.Contains(body, "r.provider.Render(templateDataMap, source)") {
		t.Errorf("should use converted variable in call, got:\n%s", body)
	}
}

func TestAllAttrNames(t *testing.T) {
	d := &generateDescriptor{
		Methods: []methodInfo{
			{SnakeName: "install"},
			{SnakeName: "remove"},
		},
		ExtraAttrs: []string{"manager", "installed", "version"},
	}
	got := tplAllAttrNames(d)
	want := `"install", "installed", "manager", "remove", "version"`
	if got != want {
		t.Errorf("allAttrNames = %q, want %q", got, want)
	}
}

func TestAllAttrNamesNoExtras(t *testing.T) {
	d := &generateDescriptor{
		Methods: []methodInfo{
			{SnakeName: "extract"},
		},
	}
	got := tplAllAttrNames(d)
	want := `"extract"`
	if got != want {
		t.Errorf("allAttrNames = %q, want %q", got, want)
	}
}

func TestHasExtraAttrs(t *testing.T) {
	with := &generateDescriptor{ExtraAttrs: []string{"manager"}}
	without := &generateDescriptor{}
	if !tplHasExtraAttrs(with) {
		t.Error("should return true when extra attrs present")
	}
	if tplHasExtraAttrs(without) {
		t.Error("should return false when no extra attrs")
	}
}

func TestNeedsImport(t *testing.T) {
	methods := []methodInfo{
		{Params: []paramInfo{{GoType: "string"}, {GoType: "bool"}}},
		{Params: []paramInfo{{GoType: "os.FileMode"}, {GoType: "string"}}},
	}
	if !tplNeedsImport(methods, "os.FileMode") {
		t.Error("should detect os.FileMode")
	}
	if tplNeedsImport(methods, "io.Writer") {
		t.Error("should not detect io.Writer when absent")
	}
	if tplNeedsImport(nil, "string") {
		t.Error("nil methods should return false")
	}
}

func TestGenerateGateRejectsCompensableBadReturn(t *testing.T) {
	r := NewGoReceiver()
	desc := buildTestDescriptor(t, []map[string]any{
		{
			"name":        "Install",
			"returns":     "(string, error)",
			"compensable": true,
			"params":      []map[string]any{},
		},
	})

	thread := &starlark.Thread{Name: "test"}
	attr, _ := r.Attr("generate")
	fn := attr.(*starlark.Builtin)
	_, err := fn.CallInternal(thread, starlark.Tuple{starlark.String(testGraphActionsTemplate), desc}, nil)
	if err == nil {
		t.Fatal("expected error for compensable method with (string, error) return")
	}
	if !strings.Contains(err.Error(), "compensable method must return") {
		t.Errorf("error should mention compensable return format: %v", err)
	}
}
